### ISSUE TITLE
Incorrect metrics/positioning of generic combining diacritics associated with a leading space.

### ISSUE THREAD

**Issue by verdy-p** [notofonts/latin-greek-cyrillic#112]
### Title 
Incorrect metrics computed when some combining diacritics are associated with a leading space (including U+0020 SPACE or preferably U+00A0 NBSP, typically used to show diacritics in isolation).  or a dotted circle

(notably: ACUTE, GRAVE and DOUBLE GRAVE accents, and DOT BELOW).
Note that these are the **most widely** used diacritics in Latin and they are used in many other pairs which may not be positioned explicitly by fonts but then cannot adopt any correct approximation (e.g. we can correctly approximate the position by assuming a base cluster width of 0.5em when positioning the combining glyph isolately with a negative horizontal offset of -0.25em).

It is possible that the glyphs where not drawn in the center of their definition cell but at a different horizontal position that should be fixed and as well as in all positioning pairs by an opposite adjustment)

### Font 
Noto Sans, Noto Sans Display

### Where the font came from, and when
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip

### Issue
  > Summarize the issue briefly -- one paragraph preferred

Testing the metrics of combining diacritics in order to render them isolately (but over a base letter drawn and center in a background layer), I see that some diacritics are incorrectly positioned.

In fact this affects some *standard* sequences with (SPACE+DIACRITIC) (standard in Unicode itself) where the effect would be to render the combining diacritic with its natural width (not reduced to 0)

  1. Steps to reproduce

Look at https://fr.wikipedia.org/wiki/Mod%C3%A8le:Table_des_caract%C3%A8res_Unicode/U0300

This is an interesting page: all generic diacritics in the U+0300 block are rendered centered in cells at the same position as the background letter o (with a gray color to distinguish the diacritic itself in back).

Note that this page does not select a specific font (on purpose), so to test it you need to open the developer console of the browser to select some background place in the page and set your prefered font.

  2. Observed results

You can see that most diacritics are correctly positioned and sized, except a few of them are drawn outside of their "natural" box, shifted to the left:

U+0300 COMBINING ACUTE ACCENT
U+0301 COMBINING GRAVE ACCENT
U+0309 COMBINING HOOK ABOVE
U+030F COMBINING DOUBLE GRAVE ACCENT
U+0323 COMBINING DOT BELOW

The set of affected diacritics may vary between several styles (italic, weight, serif/sans-serif, display, hinted or not) of Noto Fonts and we can see the effect with other Noto fonts that also include these diacritics (so the metrics data between fonts that borrowed the glyphs may not be synchronized).

You may see some variants also incorrectly positioning the dialitika+tonos (from Greek but also in the same block of generic diacritics), or the double acute accent (used in Hungarian).

  3. Expected results

The diacritics should be rendered correctly positioned. In fact, even outside such page, any text where SPACE+diacritic is used is affected (the diacritics is too much to the left).
Most probably there was a **sign error** when measuring/computing the horizontal margins, or that sign was unexpectedly dropped in some source file by a human error...

This affects more seriously pairs of letters that have no metrics for the combination, because the default metrics are taken from the combination with a (narrow) space, or sometimes from a larger character (like "m"), sometimes inconstantly.

The web page at:
https://fr.wikipedia.org/wiki/Mod%C3%A8le:Table_des_caract%C3%A8res_Unicode/U0300
can be used as a template to make a visual test of the fonts.

**Comment by simoncozens** [comment]
I think something is odd with your rendering; the font seems fine to me. Or maybe we already fixed it...

```
$ shape variable_ttf/NotoSans-VF.ttf -u 25cc,0300,25cc,0309,25cc,0364
[dottedCircle=0+594|gravecomb=0@66,4+0|dottedCircle=2+594|hookabovecomb=2@-4,4+0|dottedCircle=4+594|ecomb=4@-297,4+0]
```
![shape](https://github.com/notofonts/latin-greek-cyrillic/assets/106728/3ef54030-d9aa-4922-806c-3e447ee9fa6f)

**Comment by verdy-p** [comment]
The only thing odd is your limited test that did not include any one of the diacritics i reported above, but you testde those that are are not affected by thé reported bug.

I made a détaillée liste above with comments about each one, but you due not read scrupulously.

**Comment by simoncozens** [comment]
> you did not read scrupulously.

Please try not to assume too much about what other people do or did not do; that's rather moving this into the realm of personal insults rather than issue reporting.

> The only thing odd is your limited test that did not include any one of the diacritics I reported above,

Here is what you said above:

> You can see that most diacritics are correctly positioned and sized, except a few of them are drawn outside of their "natural" box, shifted to the left:
> U+0300 COMBINING ACUTE ACCENT
> U+0301 COMBINING GRAVE ACCENT
> U+0309 COMBINING HOOK ABOVE
> U+030F COMBINING DOUBLE GRAVE ACCENT
> U+0323 COMBINING DOT BELOW

This is why I tested whether or not the combining grave accent and combining hook above appear "drawn outside of their "natural" box, shifted to the left". They do not.

You also showed an image in your second post which showed a "stretched" rendering of combining letters above, which is why I tested that to see if I could replicate the rendering, and again I could not. This is why I closed the issue.

**Comment by verdy-p** [comment]
> You also showed an image in your second post which showed a "stretched" rendering of combining letters above, which is why I tested that to see if I could replicate the rendering, and again I could not. This is why I closed the issue.
You clearly did not made the correct test, thé proof being in your posted screenshots.
I was polite and included a single word "odd" in a reply to a msg that used it.

**Comment by verdy-p** [comment]
Ok, now this seems correct with the stretched components replaced by correctly scaled outlines with new fonts (but may be this was fixed by the system renderer in Windows 10/11 or in the shaping engine used by Google Chrome and MS Edge). The last tiem I checked, this was also incorrect on Android 10+ and in Ubuntu Linux release (all tested with the last release version of Noto, not relying on old default versions shipped with these systems).
