### ISSUE TITLE
'Combining low line' doesn't combine for dz and ts combination

### ISSUE THREAD

**Issue by dlevineBC** [notofonts/latin-greek-cyrillic#115]
### Title 
dz and ts with combing low line under each base character doesn't connect. This is for the following languages: 

- Dakelh / Southern Carrier
- Nadleh Whut'en
- Tsaaʔ Dane
- Yekooche

The ts version looks like it is connecting but I think it is just visually overlapping

### Font 
NotoSans-Regular.ttf

### Character data
d̲z̲ 
U+64 U+332 U+7A U+332

### Screenshot
Bug in rendering looks like this
<img width="185" alt="dz-noto" src="https://user-images.githubusercontent.com/29607430/55920163-a78cc080-5bad-11e9-99dc-25eaedc7cf4d.png">

Should look like this:
<img width="184" alt="dz-underline1" src="https://user-images.githubusercontent.com/29607430/55920175-b07d9200-5bad-11e9-8594-7e6bf35f7ff1.png">

The combining underline needs to vary in its width depending on the sidebearings of the base character

**Comment by moyogo** [comment]
Duplicate of  #175
