### ISSUE TITLE
NotoSans-Regular and NotoSerif-Regular (hinted) appear as italics on Windows 10

### ISSUE THREAD

**Issue by tempapy** [notofonts/latin-greek-cyrillic#12]
### Title 
NotoSans-Regular and NotoSerif-Regular (hinted) appear as italics on Windows 10

### Font 
'NotoSans-Regular.ttf' and 'NotoSerif-Regular.ttf'. 

### Where the font came from, and when
From the lastest commit (November 4th).

### Font Version
I tried 2.007 and 2.006 versions, they all have the same bug.

### OS name and version
Windows 10

### Issue
The regular fonts of NotoSans and NotoSerif appears as italics when installed with their italic, bold and bold italic counterparts.
I don't know if it happens on every software, but it happens at least with html files on firefox or chrome.

Also, "NotoSans-Regular" name is "Thin Condensed" on windows font settings.

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
![image](https://user-images.githubusercontent.com/60364152/141661685-ea99e67e-03f7-4e18-b65b-0e7dceaca037.png)

**Comment by Measureless** [comment]
Same problem since I updated to 2.008. Where can I fallback to 2.004?

**Comment by Measureless** [comment]
![image](https://user-images.githubusercontent.com/30423783/190492639-903a6a55-6c2e-4b6d-a078-1db03ad1c75e.png)
![image](https://user-images.githubusercontent.com/30423783/190492664-995496f8-ee5d-4bff-9bb0-e59056bc4abe.png)
![image](https://user-images.githubusercontent.com/30423783/190492678-78407080-fb24-4a43-9f38-5c2e5024d2f4.png)
![image](https://user-images.githubusercontent.com/30423783/190492696-ee0a7c00-091d-457c-9335-89ae231a25f9.png)

**Comment by Measureless** [comment]
![image](https://user-images.githubusercontent.com/30423783/190493118-2cc8233e-51e4-4090-ac35-0171b4e292be.png)
![image](https://user-images.githubusercontent.com/30423783/190493158-30c08c0f-4777-462e-9cbd-f10e8dde6fe5.png)
![image](https://user-images.githubusercontent.com/30423783/190493218-afe6ef19-92f8-48f2-bef6-abaede3e9a52.png)
![image](https://user-images.githubusercontent.com/30423783/190493251-f0123c65-5dd6-4051-bf9d-ba0c5912013e.png)
Maybe these Name IDs caused the problem.

**Comment by Measureless** [comment]
![image](https://user-images.githubusercontent.com/30423783/190496840-19c93210-6e25-4852-8bf8-289eba926f27.png)
I deleted these Name IDs and new problem appeared. 
![image](https://user-images.githubusercontent.com/30423783/190497176-14c14af8-49f1-4d38-bfcc-f38544858612.png)
![image](https://user-images.githubusercontent.com/30423783/190497543-0161660d-f649-450f-b996-4ea49d37fcfa.png)
Regular still displayed as italic in Chrome and Edge.
![image](https://user-images.githubusercontent.com/30423783/190497683-219207ba-609f-48e4-99ff-d3e781f0aecf.png)
![image](https://user-images.githubusercontent.com/30423783/190497709-b8e3fe3e-35be-401a-b593-b9ca9dd329af.png)
![image](https://user-images.githubusercontent.com/30423783/190497732-b02f18b4-f3ee-45ca-bb73-557683540add.png)
![image](https://user-images.githubusercontent.com/30423783/190497753-bdfa830a-ddd6-4698-862d-208f101a1546.png)
But nothing displayed wrong in Microsoft Word.
![image](https://user-images.githubusercontent.com/30423783/190498207-f7b68c80-1533-45a0-8cb7-7934f8bad974.png)
![image](https://user-images.githubusercontent.com/30423783/190498648-bd81bad5-5a76-4166-bb20-7977f1d473f8.png)
Font settings in Chrome and Edge. Regular still displayed as italic in Chrome and Edge.

**Comment by Measureless** [comment]
Maybe the PANOSE information is not correct.
![image](https://user-images.githubusercontent.com/30423783/190499565-7d1aa875-7983-4748-9f24-f80078e8b0c1.png)
![image](https://user-images.githubusercontent.com/30423783/190499614-31f9174b-c72c-4378-88f0-b08e864ed403.png)
![image](https://user-images.githubusercontent.com/30423783/190499646-a51c953f-07e2-43f4-8393-c54c721979a2.png)
![image](https://user-images.githubusercontent.com/30423783/190499705-f21093e0-e7f2-4127-af2d-e5f4f9d74bc9.png)
I will compare with version 2.004 and find the differences.

**Comment by l-uuz** [comment]
Still present in 2.011

**Comment by kal328** [comment]
As said above this is still present in v 2.011 and the earlier mention to install/use "hinted/ttf" versions is not correct.

Downloaded Noto Sans hinted ttf from 
https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/hinted/ttf 
and installing it in Windows 11 looks like this:
(Note that it may look OK for the very first time it's viewed in Setttings>Personalization>Fonts but later it will display the broken "Thin Condensed" only)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/133219564/defcc597-3b6f-450a-9af6-31d235b17053)
Noto Sans, Noto Sans Condensed, Noto Sans ExtraCondensed, Noto Sans Semicondensed all look like that. Didn't install the italic fonts.

From Noto Sans Unhinted collection at 
https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/unhinted
results are here:
Noto Sans Unhinted ttf doesn't work either, same results.
Noto Sans Unhinted variable-ttf works but only has 18 font faces.
Noto Sans Unhinted slim-variable-ttf works but only has 8 font faces.

**Comment by simoncozens** [comment]
Thanks for the detailed report! I'll take another look.

**Comment by simoncozens** [comment]
I think I may have got this now - there was a problem with a manual STAT table.

**Comment by kal328** [comment]
Is the current release, last updated 3 weeks ago, the fixed one?
Because testing from
https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/hinted/ttf
there are still glitches.

Noto Sans: Thin Condensed are wrong, rest are ok:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/133219564/8b7c665c-d36c-499b-b162-2b0b2c1dae5d)

Noto Sans Condensed looks like this:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/133219564/bf6450b7-318d-47c1-b830-14ba7b88f62d)

Noto Sans ExtraCondensed:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/133219564/4d8fb01d-2676-4ec8-92c9-0ee932b2f933)

Noto Sans SemiCondensed:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/133219564/5379e3bd-6c86-4e17-8008-39f1bb8af158)

I'd suggest you download a Windows 11 ISO for free from Microsoft and spin up a virtual machine instance to test these, instead of relying on random strangers' reports at their leisure... It should work without activation just fine, only a nag message in lower right corner.

But there has been obvious improvement, as compared to the screenshot of my previous report, thank you very much for that.

**Comment by simoncozens** [comment]
I only found the problem with this last week, so the last release does not contain the fix. Development builds at https://notofonts.github.io/latin-greek-cyrillic/ should be fixed.

**Comment by kal328** [comment]
> Development builds at https://notofonts.github.io/latin-greek-cyrillic/ should be fixed.

From that location tested Noto Sans unhinted ttf *Thin*, looks good:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/133219564/816e8b27-c4a7-4c6b-81f2-283d6efb6b0f)

Will be nice to finally be able to use these on Windows when the fixed release comes out. Thanks so much again.

**Comment by simoncozens** [comment]
Closing as the bug has been fixed in the sources. A new release of Noto Sans should be coming at the end of quarter 3. (We do a quarterly release cycle and we just had a Noto Sans release in Q2.)
