### ISSUE TITLE
Negative side-bearings on U+1D1E LATIN SMALL LETTER SIDEWAYS DIAERESIZED U

### ISSUE THREAD

**Issue by dscorbett** [notofonts/latin-greek-cyrillic#124]
### Font
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/hinted/ttf/NotoSansMono/NotoSansMono-Regular.ttf
Date: 2018-10-13

### Font version
Version 2.002; ttfautohint (v1.8.2)

### Issue
U+1D1E LATIN SMALL LETTER SIDEWAYS DIAERESIZED U has negative side-bearings.

### Character data
―ᴞ―
U+2015 HORIZONTAL BAR
U+1D1E LATIN SMALL LETTER SIDEWAYS DIAERESIZED U
U+2015 HORIZONTAL BAR

### Screenshot
![―ᴞ―](https://user-images.githubusercontent.com/1124347/46922952-ce8f7e80-cfde-11e8-9d7f-078b428469f5.png)

**Comment by simoncozens** [comment]
Someone fixed this at some point:
![shape](https://github.com/notofonts/latin-greek-cyrillic/assets/106728/a0bca792-b1e4-4b4b-90ca-3d2c24b15edb)
