### ISSUE TITLE
Printing Issues with V2.0 Noto Sans .ttf

### ISSUE THREAD

**Issue by ThomBaker** [notofonts/latin-greek-cyrillic#125]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Printing Issues with V2.0 Noto Sans .ttf
1.06 version of fonts print fine however we have issues with 2.0 additions (semibold, light in particular)

### Font 
  > NotoSansLight.ttf NotoSansSSemibold.ttf

### Where the font came from, and when
  > For example:
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip
  >   Date: 2018-08 (preferred format)

### Font Version
  > V2.0

### OS name and version
  >Microsoft Windows 10 Enterprise

### Application name and version
  > When sent to print house, output from printer

### Issue
>1. Steps to reproduce
PDF file sent to printers and printed on a black and white digital Printer 

2. Observed results
Letterforms become deformed (predominantly curves and angles)
![capture](https://user-images.githubusercontent.com/33755815/46792888-45f1b380-cd3c-11e8-9ddd-c7a1570965ad.JPG)

3. Expected results
Fonts to render as they display in pdf/indesign/onscreen

### Screenshot
![capture](https://user-images.githubusercontent.com/33755815/46792888-45f1b380-cd3c-11e8-9ddd-c7a1570965ad.JPG)

**Comment by simoncozens** [comment]
It looks like this is fixed. Let me know otherwise and I'll reopen.
