### ISSUE TITLE
Bogus zero kerning data (‘y’ + lambda)

### ISSUE THREAD

**Issue by davelab6** [notofonts/latin-greek-cyrillic#126]
Someone reported privately to me that there is bogus zero kerning data in (at least) these 2 fonts:

    NotoSerifDisplay-ExtraBoldItalic
    NotoSerifDisplay-SemiCondensedExtraBoldItalic

Their GPOS table Lookup `Index 1, LookupType 2` contains ten dubious kerning pairs with `lambda` as the second glyph, with the following glyphs as the first glyph:

    y, yacute, ydieresis, ycircumflex, chi, ygrave, uni0478, uni1EF5, uni1EF7, uni1EF9

For example, the PairSet table entry for a kerning pair between `y` and `lambda` can be found by running

    ttx -tGPOS NotoSerifDisplay-ExtraBoldIt.ttf

and it looks like this,

```xml
<PairSet index=“20”>
<!-- PairValueCount=1 -->
<PairValueRecord index=“0">
   <SecondGlyph value=“lambda”/>
   <Value1 XAdvance=“0"/>
</PairValueRecord>
</PairSet>
```

They said,

> While a zero advance value is harmless when applied for kerning, the real problem is that the offset to this dubious kerning pair falls within the next Lookup table, `Index 2, Lookup Type 4`, re-interpreting bytes intended for another purpose. Such a structure confuses some font processing programs, and suggests the fonts were not intentionally built that way.

**Comment by simoncozens** [comment]
This is no longer the case, for a number of reasons: first, our toolchain splits kerning by script (like the text layout stack does), so you can't kern a y against a lambda; second, because Noto Serif Display is no more...
