### ISSUE TITLE
NotoSans hinted: badly scaled glyphs for modifier letters at small sizes

### ISSUE THREAD

**Issue by mjansche** [notofonts/latin-greek-cyrillic#130]
### Title 
NotoSans hinted: Modifier letters such as U+02B0 MODIFIER LETTER SMALL H or U+1D50 MODIFIER LETTER SMALL M appear to be incorrectly scaled at small sizes. They appear to be scaled **up** vertically when in fact they should have been scaled down.

### Font
NotoSans-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip
Date: 2017-09-20
Downloaded: 2018-08-07

### Font Version
"Version 2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)"

### OS name and version
Unknown: The problem surfaces when printing a PDF file containing NotoSans-Regular as an embedded CID TrueType font.

### Application name and version
Ricoh MP C4503 PostScript printer

#### Steps to reproduce

Compile the following LaTeX document with `lualatex` and print it on the above-mentioned printer.
```
\documentclass[a4paper]{article}
\usepackage{fontspec}
\newfontface\notosans{NotoSans-Regular}[Path=ttf/]
\renewcommand{\baselinestretch}{3}
\begin{document}
\thispagestyle{empty}\noindent%
\notosans%
\Huge nʰ ⁿd mʰ ᵐb h\\
\huge nʰ ⁿd mʰ ᵐb h\\
\LARGE nʰ ⁿd mʰ ᵐb h\\
\Large nʰ ⁿd mʰ ᵐb h\\
\large nʰ ⁿd mʰ ᵐb h\\
\normalsize nʰ ⁿd mʰ ᵐb h\\
\small nʰ ⁿd mʰ ᵐb h\\
\footnotesize nʰ ⁿd mʰ ᵐb h\\
\scriptsize nʰ ⁿd mʰ ᵐb h\\
\tiny nʰ ⁿd mʰ ᵐb h\\
\end{document}
```

PDF file produced by lualatex: [ttf.pdf](https://github.com/googlei18n/noto-fonts/files/2266799/ttf.pdf)

####  Observed vs. expected results

![img_20180807_153005](https://user-images.githubusercontent.com/11460451/43782299-f2da5ffc-9a56-11e8-94b4-ef151b2b6213.jpg)

#### Additional information

Possibly due to an issue with the upstream autohinter.

### Character data

- U+02B0 MODIFIER LETTER SMALL H
- U+1D50 MODIFIER LETTER SMALL M
- U+207F SUPERSCRIPT LATIN SMALL LETTER N

**Comment by simoncozens** [comment]
I think this is a duplicate of #18 (or at least, #18 is the cause of the current rendering issues).
