### ISSUE TITLE
Wrong glyph for U+1FBE GREEK PROSGEGRAMMENI

### ISSUE THREAD

**Issue by dscorbett** [notofonts/latin-greek-cyrillic#135]
### Font
NotoSans-Regular.ttf
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-04-15

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+1FBE GREEK PROSGEGRAMMENI is the iota adscript, a full-sized iota to the right of a vowel, as distinguished from the iota subscript, which is a little iota below a vowel. U+1FBE should look identical to U+03B9 GREEK SMALL LETTER IOTA, to which it is canonically equivalent; it currently looks identical to U+037A GREEK YPOGEGRAMMENI, the spacing iota subscript.

### Character data
ι&#x1FBE;ͺ
U+03B9 GREEK SMALL LETTER IOTA
U+1FBE GREEK PROSGEGRAMMENI
U+037A GREEK YPOGEGRAMMENI

### Screenshot
![ι&#x1FBE;ͺ](https://user-images.githubusercontent.com/1124347/39836195-8fc25c82-53a0-11e8-91e8-f766ab929ead.png)
![ι&#x1FBE;ͺ](https://user-images.githubusercontent.com/1124347/39836197-8fd7912e-53a0-11e8-8d98-b824593e5403.png)

**Comment by simoncozens** [comment]
This has been addressed, in that U+1FBE now appears as a half-sized iota on the baseline. So it is not the same as iota, but I trust Irene for the design, and I think this is correct; although it is declared as being canonically equivalent for Unicode purposes, that just defines data processing expectations and I don't think that necessary means that it needs to be graphically identical - see [this thread](https://unicode.org/mail-arch/unicode-ml/y2008-m05/0046.html) for details.
