### ISSUE TITLE
the glyph for FEFF "ZERO WIDTH NO-BREAK SPACE" does not have a 0 advance width for some of the masters in NotoSans-ItalicMM.glyphs and NotoSansDisplay-ItalicMM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [notofonts/latin-greek-cyrillic#152]
In both NotoSans-ItalicMM.glyphs and NotoSansDisplay-ItalicMM.glyphs the glyph "uniFEFF" (for the character "ZERO WIDTH NO-BREAK SPACE") does not have a 0 advance width for all the masters: some of the masters have a positive width (the largest width for ZERO WIDTH NO-BREAK SPACE is over 900 and the smallest non-zero is 4). This causes interpolation problems.

**Comment by simoncozens** [comment]
Yes, these are all zero width now.
