### ISSUE TITLE
Last version of Noto Sans not working with Microsoft Word

### ISSUE THREAD

**Issue by joseterreiro** [notofonts/latin-greek-cyrillic#153]
Lastest version of Noto Sans ("Version 2.000;GOOG;noto-source:2017915;90ef993387c0; ttautohint (v1.7)") doesn't work in Microsoft Word.

I mean, the fonts downloaded from Google Noto Fonts (google.com/get/noto/).  The fonts from Google Fonts (fonts.google.com)--version 1.04--work just fine. The problem is that Google Fonts only have the four standard styles (regular, italic, bold and bold italic).

Is it a bug or the new Noto Sans version is not ready yet?

Thank you.

José T.

**Comment by simoncozens** [comment]
> But I am trying to find a sans serif typeface that works with Microsoft's equation editor, and am disappointed to learn that Noto Sans Math is not one only after installing it.

Yes, sorry; we will get there! The adding of the MATH table is now being carried out by another team; they have a font ready and it's being reviewed, but there are also questions about how to add the MATH table using our toolchain. Anyway, that is an issue for notofonts/math.

*This* issue here (about using Noto fonts with Word) seems to have been resolved with recent builds of different Noto fonts. If not, please open issues in the [relevant font repository](https://notofonts.github.io/reporter.html))
