### ISSUE TITLE
‎A7AE is a capital letter not a lowercase letter.

### ISSUE THREAD

**Issue by moyogo** [notofonts/latin-greek-cyrillic#154]
Noto Sans, Noto Serif and Noto Sans Mono (Version 2.000 from https://www.google.com/get/noto/ or https://github.com/googlei18n/noto-fonts-alpha) have the wrong shape for ‎U+A7AE.

U+A7AE Ɪ is the uppercase of U+026A ɪ. While U+026A ɪ is a x-height smallcap serifed i, its uppercase must have cap-height and be a serifed I (preferably wider or thicker serifs that look like top and bottom bars, similar to the top bar of the T, to differentiate it from the letter U+0049 I if it has serifs like in Noto Sans and Noto Sans Mono).

For example, here is IiꞮɪ <0049, 0069, A7AE, 026A>:
![notosans-regular-ii](https://user-images.githubusercontent.com/1923747/34648767-68b80456-f398-11e7-8505-82c66cb05b74.png)
In Noto Sans, A7AE Ɪ should be as tall as 0049 I, with wider serifs or top and bottom bars to help differentiating it from 0049 I since both are used in the same language orthography.

![notosansmono-regular-ii](https://user-images.githubusercontent.com/1923747/34648791-f0912420-f398-11e7-9a22-2144600ab2c3.png)
Same as Noto Sans.

![notoserif-regular-ii](https://user-images.githubusercontent.com/1923747/34648780-d36ad1d4-f398-11e7-90fc-540da453ee4c.png)
In Noto Serif, A7AE Ɪ should be as tall as 0049 I, its top and bottom bars are fine.

Compare with the *correct* shapes in Arial 6.98 and Times 6.98:
![arial-regular-ii](https://user-images.githubusercontent.com/1923747/34648820-8f888032-f399-11e7-8915-054617f3ff39.png)
![times-regular-ii](https://user-images.githubusercontent.com/1923747/34648893-625d2232-f39b-11e7-87bd-918844cd652d.png)
or Ɪɪ <A7AE, 026A> and their actual smallcap in the work-in-progress Brill (to keep in mind for notofonts/latin-greek-cyrillic#160):
https://twitter.com/TiroTypeworks/status/807321889748041728

**Comment by verdy-p** [comment]
This still does not seem to be fixed in "NotoSansMono[-Regular/Bold/Italic]" and "NotoSansDisplay[-Regular/Bold/Italic]"
But only in "NotoSans[-Regular/Bold/Italic]" and "NotoSerif[-Regular/Bold/Italic]"
(I've not looked into the "variable" font variants)

**Comment by moyogo** [comment]
@verdy-p
> This still does not seem to be fixed in "NotoSansSerif-[Regular/Thin/Bold/Black/Italic]" and "NotoMonoDisplay-[Regular/Thin/Bold/Black/Italic]".

What do you mean? There is no NotoSansSerif, there is no NotoMonoDisplay.
Display variants are not being worked on until further notice.

**Comment by verdy-p** [comment]
Sorry, this should have been Mono only without the Display, an incorrecte
copy-paste with a forgotten edit.

**Comment by moyogo** [comment]
OK, I think I see what you mean. I'll update the top and bottom bars in Noto Sans Mono to match Noto Sans.
