### ISSUE TITLE
Combining diacritics above space characters too much at the left

### ISSUE THREAD

**Issue by sommerluk** [notofonts/latin-greek-cyrillic#158]
Noto (LGC) current alpha release from pipeline, regular style, using InDesign under Windows 10 (creators update).

When using combining diacritics above space characters (space, thin space, non-breaking space) then they seem to be too much at the left:

![screenshot 1](https://user-images.githubusercontent.com/6830724/27181554-8d7ae88a-51c7-11e7-93a8-8629cb35d55a.png)

Sequence:
U+0048 LATIN CAPITAL LETTER H
U+0020 SPACE [SP]
U+02CB MODIFIER LETTER GRAVE ACCENT
U+0048 LATIN CAPITAL LETTER H

I would expect the diacritics to be more in the center between the two H characters.

**Comment by simoncozens** [comment]
This seems to be fine now.
