### ISSUE TITLE
U+203F in Noto Serif  should not be combining.

### ISSUE THREAD

**Issue by survtur** [notofonts/latin-greek-cyrillic#16]
UNDERTIE U+203F ‿  that is in Noto Serif is incorrect. It should not be combining symbol.

**Comment by simoncozens** [comment]
This appears to be fixed now; it has advance width:

$ shape fonts/NotoSans/googlefonts/ttf/NotoSans-Regular.ttf -u 203f
[uni203F=0+609]
![shape](https://user-images.githubusercontent.com/106728/211042333-bfedf445-2450-4d70-83d2-098617ee3d4f.png)
