### ISSUE TITLE
Imporve Dinka langauge support in Noto Sans and Noto Serif families

### ISSUE THREAD

**Issue by andjc** [notofonts/latin-greek-cyrillic#162]
The Dinka language like many African languages uses the n-form of U+014A LATIN CAPITAL LETTER ENG. The Noto fonts default to the N-form. Noto Sans provides three versions of the glyph, but only supplied access to the alternative glyphs using the aalt feature. This is useful for applications such as Indesign, but isn't really suitable for web development. 

I would suggest:
1) add a cvNN feature to access the variant glyphs for U+014A
2) add the DNK OT language system (for applications that provide adequate locl support) - requires Eng.alt1 glyph

**Comment by simoncozens** [comment]
This appears to be another Eng selection issue, which we'll track at #161. We will fix this, but part of fixing it is getting organised about the scope of changes required.

**Comment by andjc** [comment]
@simoncozens for proper Dinka support you also need to tick off ïï and ÏÏ as well, probably also the high tone equivalents as well as per unified orthography and grammar. But that probably needs to be separate issues.

**Comment by simoncozens** [comment]
We have those, but they need kerning. I'm aware of it!
