### ISSUE TITLE
Noto Sans, Noto Serif: wrong U+A7FA small capital turned m

### ISSUE THREAD

**Issue by moyogo** [notofonts/latin-greek-cyrillic#165]
U+A7FA small capital turned m should look like a Cyrillic small capital sha (that is small capital of U+0428). It is currently only correct in Noto Serif (roman) and is incorrect in Noto Sans (roman and italic) and Noto Serif (italic).

See "ꟺ" in Noto Sans and Noto Serif:
![screen shot 2017-02-19 at 4 31 28 pm](https://cloud.githubusercontent.com/assets/1923747/23104188/e656933a-f6c0-11e6-9d9e-54931040e9f0.png)

See Unicode chart http://www.unicode.org/charts/PDF/UA720.pdf and encoding proposal http://www.unicode.org/L2/L2009/09028-n3571-upa-additions.pdf for reference.

**Comment by simoncozens** [comment]
This is fixed in Noto Sans/Serif and Arimo/Tinos/Cousine are frozen.
