### ISSUE TITLE
Check if Noto Sans+Serif covers Twi

### ISSUE THREAD

**Issue by brawer** [notofonts/latin-greek-cyrillic#174]
On https://groups.google.com/forum/#!topic/noto-font/ARPRO9BlSb8, we got a report that Noto might not work with Twi. We do list Akan [ak] as a supported language on google.com/get/noto, but not Twi [tw]. Maybe we just need to add Twi to the list of supported languages. On the other hand, according to Omniglot, there are accented letters in [Twi](http://www.omniglot.com/writing/twi.htm) but not in [Akan](http://www.omniglot.com/writing/akan.htm). While we’re at it, we should also check the accents needed for writing [Ga](http://www.omniglot.com/writing/ga.htm).

**Comment by simoncozens** [comment]
I'm not sure where this issue is up to. From what I can gather, Noto Sans+Serif's codepoint coverage is fine for Twi, but there are questions about the appropriate form of the eng glyph... and then the topic started to drift.

@moyogo / @NeilSureshPatel, do you know more?

**Comment by andjc** [comment]
@simoncozens  my understanding is that: the fonts, as they were, supported Twi. Only extended Latin requirements were open-e and open-o.

Although I cann't remember if font substring on Google Fonts impacted Two.

Most of the discussion is more related to need for a strategy or technical approach to handling African languages.An area with Noto fonts are notoriously poor at.

**Comment by simoncozens** [comment]
> Although I can't remember if font subsetting on Google Fonts impacted Twi, and whether that was at the root of the report.

That's quite likely. I'll take a look at that.

> Most of the discussion is more related to need for a strategy or technical approach to handling African languages.An area with Noto fonts are notoriously poor at.

Well, there's a reason I tagged Neil Patel! African language support for Noto is something we're working on.

**Comment by simoncozens** [comment]
> I'll take a look at that.

Yeah, it looks like we subset out ɛ, ɑ, ɔ, and probably other stuff as well. This is a https://github.com/googlefonts/glyphsets issue, so I'll reopen over there and link here.
