### ISSUE TITLE
Latin upsilons design issues

### ISSUE THREAD

**Issue by moyogo** [notofonts/latin-greek-cyrillic#179]
See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman and then in italic: Ʊʊᶷᵿꭥ (U+01B1 U+028A U+1DB7 U+1D7F U+AB65)
![screen shot 2015-09-04 at 07 58 03](https://cloud.githubusercontent.com/assets/1923747/9678239/bf55c188-52da-11e5-92b9-572900e7267b.png)

In Arimo and Cousine, ᵿ U+1D7F should match ʊ U+028A, or the other way around. Update: removed note about ꭥ U+AB65.

In Tinos, ꭥ U+AB65 is unnecessarily large, it should have a normal x-height, meaning be just a turned ʊ U+028A.

Noto Sans and Noto Serif are good, ꭥ U+AB65 is missing.

**Comment by simoncozens** [comment]
I think what's left in Noto here is a (potential) weight inconsistency with Omegasmall in the Sans. Here's  ʊꭥΩo:

<img width="746" alt="Screenshot 2023-01-19 at 13 29 52" src="https://user-images.githubusercontent.com/106728/213455173-f4d6630a-195f-4d9e-aafe-b34ed54ea729.png">

If my eyes aren't deceiving me, ꭥ is a bit lighter than the others. I could just flip ʊ to make ꭥ, but I don't know if there would need to be visual corrections here. Needs an actual designer.
