### ISSUE TITLE
Latin alphas ɑ U+0251, ɒ U+0252, ꭤ U+AB64 should have better shapes

### ISSUE THREAD

**Issue by moyogo** [notofonts/latin-greek-cyrillic#180]
The Latin alphas ɑ U+0251, ɒ U+0252, ꭤ U+AB64 should have shapes that 
- help them work together, they should be distinguishable from each other as they are used to represent different sounds in phonetic transcription
- help U+0251 be different from a U+0061 in italic as some languages use U+0251 and its uppercase as an orthographic letter along with U+0061 and its uppercase. Some phonetic transcriptions also use these in italic and need the distinction.

See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman: ɑɒꭤ (U+0251 U+0252 U+AB64); and in italic: aɑɒꭤ (U+0061 U+0251 U+0252 U+AB64)
![screen shot 2015-09-04 at 07 06 05](https://cloud.githubusercontent.com/assets/1923747/9677565/841799a4-52d3-11e5-8596-89c1693a825d.png)

These have design issues or have distinctions only visible at large sizes.

Solutions:
To help distinguish between ɒ U+0252 and ꭤ U+AB64:
- add a hooked-tail terminal to the Latin alpha can make the shapes distinguishable.
  There are a few ways to make the Latin alphas look different from the Latin a as well:
- no hooked-tail terminal on single-storey Latin a;
- have a slightly diagonal stem on the Latin alphas in italic (or maybe even in roman);
- provide a double-storey a for U+0061 as a stylistic alternate.

In Arimo Regular and Bold, the glyph of ꭤ is based on the Greek alpha but in Italic and Bold Italic is it based on the Latin alpha. The Latin alpha should have a hooked-tail terminal like the italic double-storey a does so ɑ U+0251 can have a bottom-right tail, ɒ U+0252 a top-left tail and ꭤ U+AB64 a top-right tail.

In Cousine, ɑ U+0251 can have a bottom-right tail, ɒ U+0252 a top-left tail, ꭤ U+AB64 is missing.

In Tinos, a double-storey stylistic alternate for Latin a U+0061 could be provided.

In Noto Sans, ɑ U+0251 can have a bottom-right tail, ɒ U+0252 a top-left tail, ꭤ U+AB64 is missing.

In Noto Serif, a double-storey stylistic alternate for Latin a U+0061 could be provided

**Comment by simoncozens** [comment]
It looks like Noto is fixed here. There may be issues in Arimo/Cousine/Tinos but (this is probably a strange place to announce it) development on those fonts is essentially frozen from our perspective. (Of course as open source fonts, others are welcome to fork and develop as needed!)

**Comment by fitojb** [comment]
Let’s hope that the Liberation font project continues to develop the design, then
