### ISSUE TITLE
Thin space advance width variant for French?

### ISSUE THREAD

**Issue by dougfelt** [notofonts/latin-greek-cyrillic#182]
Roboto had this issue, that was fixed:

[Width of U+2009 THIN SPACE may need to be modified for French notofonts/noto-fonts#24](https://github.com/google/roboto/issues/24)

But it might apply to Noto LGC as well.  At any rate, the lint tool doesn't do any language-specific checks, so if there was a variant of thin space for French we wouldn't know about it

**Comment by simoncozens** [comment]
I think this has been resolved, in that thinspace and narrownbspace have both been set to 1/6th of em, which visually should work nicely for French.
