### ISSUE TITLE
U+031A COMBINING LEFT ANGLE ABOVE is misplaced

### ISSUE THREAD

**Issue by jungshik** [notofonts/latin-greek-cyrillic#183]
Moved from googlei18n/noto-alpha#259. 

Imported from [Google Code issue notofonts/noto-fonts#259](https://code.google.com/p/noto-alpha/issues/detail?id=259) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T02:34:59.000Z:

---

In Noto Sans and Noto Serif, the character is misplaced. Compare the rendering of the sequences d̚  and g̚  in Noto, Calibri, and DejaVu.

The two examples above can be found in pages ix and 17 of the IPA handbook.

The first is Calibri and the 2nd and the 3rd are Noto Sans and Noto Serif. 

![calibri](https://cloud.githubusercontent.com/assets/12721521/8659749/acd58694-2961-11e5-921f-3ddbe3bab143.png)
![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8659750/ace6da5c-2961-11e5-9297-b868d9f61594.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8659751/aceb37fa-2961-11e5-95ab-8e6890f4cf0e.png)

**Comment by moyogo** [comment]
I’ll do a PR.

**Comment by moyogo** [comment]
This may better illustrate the issue with just d̚:
| IPA chart | Noto Sans | Noto Serif|
|--|--|--|
| <img width="82" alt="Screenshot 2023-01-26 at 20 49 34" src="https://user-images.githubusercontent.com/1923747/214935790-2252df6a-38eb-4a12-97c6-95699702b58f.png"> | <img width="48" alt="Screenshot 2023-01-26 at 20 48 53" src="https://user-images.githubusercontent.com/1923747/214935635-abd7e7cc-d79f-4b9b-9829-17f3255eb08d.png">| <img width="48" alt="Screenshot 2023-01-26 at 20 52 05" src="https://user-images.githubusercontent.com/1923747/214936294-a2852ec1-81aa-4a62-b995-8aad829d2c1a.png"> |

**Comment by simoncozens** [comment]
It looks like it should just be a spacing base glyph, right?
