### ISSUE TITLE
Noto Sans Mono's alphabet O and number 0 issue

### ISSUE THREAD

**Issue by YunsuChoi** [notofonts/latin-greek-cyrillic#188]
<img width="167" alt="2017-04-04 19 22 01" src="https://cloud.githubusercontent.com/assets/1073023/24652228/01180ba4-196c-11e7-843b-ed63e73fa997.png">

As we know, sometimes Alphabet Upper O or Lower case o is confused with number zero(0). especially for programming, it is very import issue. to solve this problem most of coding fonts(example D2 Coding) are has slash line in number zero. 
but as we see the attachment, Noto Sans Mono font is super confuse to identify O or 0. 
should fix this problem. for current state, Noto Sans Mono is unusable.

**Comment by simoncozens** [comment]
The zero has been modified to have a slash applied:

![shape](https://user-images.githubusercontent.com/106728/211050475-7f08650e-2110-414c-a956-dced0e7ec93b.png)

**Comment by JimEBlevins** [comment]
Today, in Libre Office's Writer, the character-options did not work for zero. The unicode or CSS tags zero=0 and zero=1 had the same effect. (This may be a bug with Libre Office.) 

Many Norwegians and Danes prefer a _dotted_ zero or a slash that is less vertical. The current slashed-zero is easily confused with the Scandinavian "œ" ["oe"] character ø & Ø (ö & Ö in Swedish). 
[In GitHub's font, these look too much like the empty set ∅ ....]

Here is a suitable slashed zero from **Iosevka**: 
![image](https://raw.githubusercontent.com/be5invis/Iosevka/e14bfb80be04a4b626cd3514574f6500986246d8/images/cv-zero-slashed.light.svg)

I would like a character variant of a (more horizontal) slash, a dot, and a plain zero, please.
