### ISSUE TITLE
Mono alpha: bracketleft and bracketright are not vertically aligned

### ISSUE THREAD

**Issue by codeman38** [notofonts/latin-greek-cyrillic#189]
In the alpha version of Noto Sans Mono, the characters `[` (bracketleft) and `]` (bracketright) are not vertically aligned with each other in many weights. The exact amount of this discrepancy seems to differ across weights, which suggests that this is likely an interpolation issue.

Font | Lowest Point of [ | Lowest Point of ]
--|--|--
NotoSansMono-Light.ttf | -158 | -153
NotoSansMono-Regular.ttf | -158 | -148
NotoSansMono-Bold.ttf | -162 | -155
NotoSansMono-Black.ttf | -168 | -168

**Comment by simoncozens** [comment]
It is fixed now:

<img width="832" alt="Screenshot 2023-02-03 at 12 53 43" src="https://user-images.githubusercontent.com/106728/216608317-65bcad16-60cc-4e89-a2e5-869df68fefc8.png">
