### ISSUE TITLE
Noto Mono, Serif and Sans: Super OpenType/CFF Collection (Super OTC) Release?

### ISSUE THREAD

**Issue by kphillisjr** [notofonts/latin-greek-cyrillic#193]
This is mostly a request to bring an all in one release similar to what is seen with Noto Sans CJK, and Noto Serif CJK. The main improvement this font format has is to reduce the number of font files installed to get all variations, and to reduced overall disk space usage.

**Comment by simoncozens** [comment]
I think we're unlikely to do this, now that variable fonts allow us to have all the styles in a single, efficient file.
