### ISSUE TITLE
Noto Sans Mono: Glyph for U+2026 HORIZONTAL ELLIPSIS wrong

### ISSUE THREAD

**Issue by sommerluk** [notofonts/latin-greek-cyrillic#194]
Noto Sans Mono: Glyph for U+2026 HORIZONTAL ELLIPSIS wrong

In Noto Sans Mono, the glyph for U+2026 HORIZONTAL ELLIPSIS seems to be simply the same glyph as for U+002E FULL STOP.

Usually this glyph is designed as three dots. Having a simple dot seems a little bit strange…

**Comment by simoncozens** [comment]
Yes, these two glyphs are now fixed.
