### ISSUE TITLE
Will there be APIs available for using the whole sets of weights and widths of Noto Sans/Serif since Phase 3?

### ISSUE THREAD

**Issue by ytxmobile98** [notofonts/latin-greek-cyrillic#198]
As stated above.
Currently Google Fonts API only supports Regular/Italic/Bold/Bold Italic.

**Comment by simoncozens** [comment]
This is (slowly) happening. Noto Serif variable is already on fonts.google.com; Noto Sans is making its way through the pipeline but there are still a few wrinkles to be ironed out. Definitely this year and hopefully this quarter.
