### ISSUE TITLE
Noto Sans light, semibold, etc. are not present on Google Fonts

### ISSUE THREAD

**Issue by collimarco** [notofonts/latin-greek-cyrillic#225]
Hello,

I would like to use **Noto Sans on a website**.

However I noticed that Google Fonts has only the weight 400 and 700:
https://fonts.google.com/specimen/Noto+Sans?query=noto+sans

**Why aren't the other weights present? I mean, why 100, 200, 300, 500, 600 are not listed on Google Fonts?**

I see on the official website that those weights exist! 
https://www.google.com/get/noto/

**Can I download all the Noto Sans weights (e.g. light, semibold) and host them directly on my website? Is that allowed by the license?**

I tried to read the help page but it is not clear... It seems to suggest to use Google Fonts Early Access (!?)

> For use in web content: it is very important to use the fonts as web fonts. When a font is only specified in CSS font-family but not really delivered to the client as a web font, the browser will automatically fall back to another font. Some Noto fonts are available at Google Web Fonts Early Access. However, sometimes, it doesn’t serve the latest version of Noto or provides a subset of a font. 
> https://www.google.com/get/noto/help/guidelines/

**Comment by simoncozens** [comment]
Duplicate of #14. We are getting there, and will be onboarding the variable versions soon.
