### ISSUE TITLE
fsSelection/MacStyle incorrect in Noto Sans?

### ISSUE THREAD

**Issue by moontypespace** [notofonts/latin-greek-cyrillic#227]
## Defect Report
I checked the latest Noto fonts stored on GitHub ('noto-fonts/hinted/ttf'):
NotoSans-Bold.ttf (Version 2.007)
NotoSans-BoldItalic.ttf (Version 2.008)
NotoSans-Italic.ttf (Version 2.008)
NotoSans-Light.ttf (Version 2.007)
NotoSans-LightItalic.ttf (Version 2.008)
NotoSans-Medium.ttf (Version 2.007)
NotoSans-MediumItalic.ttf (Version 2.008)
NotoSans-Regular.ttf (Version 2.007)

### Issue
The following static Fonts have a STAT table (but shouldn't):
NotoSans-Bold.ttf (Version 2.007)
NotoSans-Light.ttf (Version 2.007)
NotoSans-Medium.ttf (Version 2.007)
NotoSans-Regular.ttf (Version 2.007)

They also have a bunch of name table entries above name ID 255. 
For me it looks like there went something wrong during the building process. It looks like it has all the variable font instance and axes names. Even though it's not a variabel font.

Some fonts have the WWS bit set in the OS/2 table fsSelection, some don't. Is this intended to be like that or a bug? However, it is inconsistent. 

'NotoSans-Bold.ttf' the 'Bold' bit is not set in (style linking issue):
OS/2 table fsSelection
head table macStyle

I have reported this issue already a couple month ago:
https://github.com/googlefonts/noto-fonts/issues/2279
And it seems to be fixed in the sources, but not in the final fonts. 

Would be great if someone would like to take care of the mentioned issues and update the fonts.

Thanks, 
Olli

**Comment by xctvcd** [comment]
I’d like to second this, any news here?

**Comment by Measureless** [comment]
Same problem. #12

**Comment by simoncozens** [comment]
OK, I'll take another look.

**Comment by xctvcd** [comment]
@simoncozens did you get around to looking?

**Comment by simoncozens** [comment]
This appears to be fixed, to me:

```
$ wget https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/hinted/ttf/NotoSans-Bold.ttf
$ ttx -o - -t OS/2 NotoSans-Bold.ttf | grep fsSelection
Dumping "NotoSans-Bold.ttf" to "-"...
Dumping 'OS/2' table...
    <fsSelection value="00000000 10100000"/>
$ ttx -o - -t head NotoSans-Bold.ttf | grep macStyle
Dumping "NotoSans-Bold.ttf" to "-"...
Dumping 'head' table...
    <macStyle value="00000000 00000001"/>
```

So bit 5 of fsSelection and bit 0 of macStyle are both set, as they should be. Seems fine?

**Comment by simoncozens** [comment]
I believe I've fixed the problem here; the issue was that all of the statics were inheriting the STAT table of the variable. Bit 7 should be set as we are requiring typo metrics. None of the fonts use bit 8 any more.
