### ISSUE TITLE
Noto Sans: missing U+266A Eighth Note and U+266B Beamed Eighth Notes for complete subtitle support

### ISSUE THREAD

**Issue by thlinard** [notofonts/latin-greek-cyrillic#229]
### Noto Sans: missing U+266A Eighth Note and U+266B Beamed Eighth Notes for complete subtitle support

♪ U+266A Eighth Note use is defined as such in Netflix Timed Text Style Guide:

> "I.15. Songs
> Song lyrics should be enclosed with a music note (♪) at the beginning and the end of each subtitle."

https://partnerhelp.netflixstudios.com/hc/en-us/articles/217350977-English-Timed-Text-Style-Guide

♫ U+266B Beamed Eighth Notes use is defined as such in BBC Subtitle Guidelines:

> "9.3.2 Characters permitted online
> In addition to the characters above, the following characters are allowed if the subtitles are intended for online use only.
> online € ♫ (replaces # to indicate music) ← → (arrows can replace < and >)."

https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Characters-permitted-online

Both characters are widely used in subtitles. They should be included in Noto Sans charset for full subtitle support.

The glyphs are already in Noto Music and Noto Sans Symbols.

**Comment by simoncozens** [comment]
There is a scope question here (should Noto Sans aim for "full subtitle support"?) but the fix is fairly clear.

**Comment by aelatham** [comment]
Please close as "not planned".

**Comment by simoncozens** [comment]
Yep, adding new characters is not a free operation. This glyphs are already covered.
