### ISSUE TITLE
Please include variable versions of Noto Sans and Noto Serif in Google fonts

### ISSUE THREAD

**Issue by RodneyAraujo** [notofonts/latin-greek-cyrillic#231]
## Defect Report
Please update the noto sans and noto serif fonts in Google Fonts to variable versions

**Comment by simoncozens** [comment]
This is happening.

Serif is already making its way to Google Fonts, give it a week or so: https://github.com/google/fonts/pull/6134
Sans is in QA and should be there soon: https://github.com/google/fonts/pull/5789
