### ISSUE TITLE
Musical Flat Symbol

### ISSUE THREAD

**Issue by etsnyman** [notofonts/latin-greek-cyrillic#232]
Hi there!

There is already a sharp (♯) (not hashtag) symbol available in Noto Sans.

How can we go about getting a Flat (♭) symbol in too?

The Droid Sans Fallback font already includes this glyph. Surely it is a case of copy-paste?

**Comment by simoncozens** [comment]
Someone fixed this by removing the musical sharp from Noto Sans. Thanks for doing this, whoever it was! (But please close issues when you fix them... ;-)
