### ISSUE TITLE
Standalone diacritics combine with the next letter in Noto Serif

### ISSUE THREAD

**Issue by jens-lilt** [notofonts/latin-greek-cyrillic#236]
### Title 
When rendering text with a backtick, the backtick combines with the next letter in Noto Serif Latin.

### Font 
noto-serif-v21-latin-regular (possibly others as well)

### Where the font came from, and when
Google webfonts helper
https://google-webfonts-helper.herokuapp.com/fonts/noto-serif?subsets=latin
Date: 2022-07-01

### Font Version
Version 21

### OS name and version
Mac OS Monterey 12.4

### Application name and version
Google Chrome and Firefox

### Issue
When rendering text with a backtick (U+0060, not combining backtick U+0300), the backtick combines with the next letter in Noto Serif Latin.
<img width="150" alt="Screenshot 2022-07-01 at 09 13 48" src="https://user-images.githubusercontent.com/97596764/176843796-f1d27f6f-72a9-41a0-8781-001d548ffceb.png">

Any text which has the Noto Serif font applied will exhibit the combining diacritics behavior even for the normal backtick U+0060.

Example HTML
[noto.zip](https://github.com/notofonts/latin-greek-cyrillic/files/9026867/noto.zip)

**Comment by simoncozens** [comment]
The version you provided was 1.003:
![shape](https://user-images.githubusercontent.com/106728/211048365-bfba2ff1-0672-4dbf-b93f-91c29660ab82.png)

The problem appears to have been fixed, as of v2.009:
![shape](https://user-images.githubusercontent.com/106728/211048452-0289272f-e2c5-4c54-8cde-2a07dd28afde.png)
