### ISSUE TITLE
Request for null sign ∅ U+2205

### ISSUE THREAD

**Issue by Linguistx** [notofonts/latin-greek-cyrillic#28]
## Defect Report
> All Noto fonts appear to be missing Unicode character U+2205. This is used in mathematics and linguistics: https://en.wikipedia.org/wiki/Null_sign

### Font 
  > Seems to be all Noto fonts, at very least isn't in 'NotoSerif-Regular.ttf' and 'NotoSans-Regular.ttf'.

Thank you!

**Comment by simoncozens** [comment]
I think I'm going to close this; while I understand that the null sign is used in linguistics, it's not part of IPA for whatever reason and as a specialist (mathematical) symbol it doesn't really belong in a Latin/Greek/Cyrillic font. There's a kind of "where would it end?" situation if we start grabbing some mathematical glyphs and adding them into Noto Sans/Serif.

Noto fonts are always meant to be used in the context of a rendering stack where the text engine finds the most appropriate font for the Unicode codepoints being typed - which goes particularly for linguistics settings where you are often using characters from different scripts! As others have mentioned, if you need to, there are ways to merge multiple fonts together. Sorry!
