### ISSUE TITLE
Noto Sans: Vietnamese's ngã "tumbling" tone is just a horizontal line but not a `(low) falling and (mid) rising` or `creaking-rising`

### ISSUE THREAD

**Issue by samdx** [notofonts/latin-greek-cyrillic#301]
Hi,

The following image shows the comparition between Noto Sans vs Lato Sans in displaying the Vietnamese's [ngã](https://en.wikipedia.org/wiki/Vietnamese_phonology#Six-tone_analysis) tone.

Here you can see, Noto Sans displays this tone just weird. It's a - (horizontal-line) instead of a ~.

The text in the left side was used Noto Sans font, and Lato is the right one, in comparision of displaying of the word `gõ` (the 2nd word from left in the example sentence).

My question, why it is and how to fix that?

Thanks.

![Noto Sans vs Lato Sans in Vietnamese's ngã tone](https://cloud.githubusercontent.com/assets/18287802/18922336/59baa11e-85d2-11e6-9d59-99892259b295.png)

(Really sorry for this so small font size!)

**Comment by ethanc8** [comment]
@nizarsq 
> This issue seems to be fixed for NotoSans, NotiSerif and NotoSansMono <img alt="Screen Shot 2020-07-21 at 9 52 01 PM" width="581" src="https://user-images.githubusercontent.com/22158882/88135628-6949c380-cb9c-11ea-8a7f-6f76d722f9ce.png">

I can still reproduce the issue, on KDE Neon (Ubuntu 22.04 derivative) with the preinstalled Noto fonts. Where can I access the document that you screenshotted?

**Comment by ethanc8** [comment]
Also, the relevant FreeType bug seems to be moved to https://gitlab.freedesktop.org/freetype/freetype/-/issues/112.
