### ISSUE TITLE
Noto Serif: Missing Unicode arrows

### ISSUE THREAD

**Issue by ghost** [notofonts/latin-greek-cyrillic#32]
## Defect Report

Noto Serif appears to be missing Unicode characters.

``` bash
$ wget https://github.com/googlefonts/noto-fonts/raw/master/hinted/ttf/NotoSerif/NotoSerif-Bold.ttf
$ wget https://github.com/googlefonts/noto-fonts/raw/master/hinted/ttf/NotoSerif/NotoSerif-BoldItalic.ttf
$ wget https://github.com/googlefonts/noto-fonts/raw/master/hinted/ttf/NotoSerif/NotoSerif-Italic.ttf
$ wget https://github.com/googlefonts/noto-fonts/raw/master/hinted/ttf/NotoSerif/NotoSerif-Regular.ttf
```

### Font Version
Latest from repo at time of writing.

### Application name and version
[KeenWrite](https://github.com/DaveJarvis/keenwrite), on main branch.

### Issue
[Unicode arrows](http://xahlee.info/comp/unicode_arrows.html) do not appear to be included in Noto Serif.

### Screenshot
Noto Sans is on the left, Noto Serif shows tofu on the right:

![keenwrite-tofu](https://user-images.githubusercontent.com/2131950/102026408-82712d80-3d52-11eb-9a8c-99b5ca30fd90.png)

### FontForge

Noto Serif:

![font-forge](https://user-images.githubusercontent.com/2131950/102026684-feb84080-3d53-11eb-9f4e-7fd2c7d79459.png)

Noto Sans has a few arrows defined:

![noto-sans](https://user-images.githubusercontent.com/2131950/102026744-7e460f80-3d54-11eb-98ba-79526d1c324b.png)

Having the equivalent glyphs in both releases would be sublime.

## Addendum

The application uses [FlyingSaucer](https://github.com/flyingsaucerproject/flyingsaucer), which doesn't support a fallback font.

## Feature Request

Minimally, merging the Unicode arrows from Noto Sans into Noto Serif would be a good starting point.

**Comment by aelatham** [comment]
We should consolidate the missing characters issues (others are #229 #233 #468 #469) into one big issue.

**Comment by aelatham** [comment]
Please close as "not planned", per the comment on the big issue.
