### ISSUE TITLE
Noto Sans Mono 'r' glyph has serifs

### ISSUE THREAD

**Issue by ataraxia937** [notofonts/latin-greek-cyrillic#341]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
The lower-case 'r' glyph in the new Noto Sans Mono has large serifs. None of the other Latin letters have them.

### Font 
NotoSansMono-Regular.ttf:

### Where the font came from, and when
Arch Linux distribution
Date: 2018-04-04

### Font Version
131072
  
### OS name and version
Arch Linux (current)

### Issue
The lower-case 'r' glyph in the new Noto Sans Mono has large serifs - a bar across the bottom and an extension to the left from the top of the letter. None of the other Latin letters have similar elements.
The same glyph in Noto Sans is much more appealing.

**Comment by Nico314159** [comment]
> @jonhoo and @joshuakraemer I broadly agree with @moyogo and explained a little more in https://github.com/googlefonts/noto-fonts/issues/1253#issuecomment-665757225 - the image @joshuakraemer posted here seems to me to illustrate the 'swiss cheese' effect of too-much and uneven whitespace in the `Noto Mono` design, so I am skeptical about reverting to a sans-serif `r` as a default design form. However, if the sans-serif `r` is no longer available, retaining it in a stylistic set seems like an issue that can be addressed; and folks like @luaraneda can then use the new 2020 era noto-build tools to 'freeze' such a feature into the default design if they can't configure their terminal/app to use OpenType features.
> 
> @marek and I and Monotype folks discussed this naming issue and I don't feel strongly about it, but MT folks pointed out that family renaming can be disruptive for users. However, it seems `Noto Mono` was the original name, then it was renamed to `Noto Sans Mono` with design changes like the addition of the serifs, and this week Marek has renamed it back to `Noto Mono` :) So, the naming is not super simple. My soft recommendation is to retain the `Noto Sans Mono` name, simply to minimize disruption.

The issue is that "stylistic sets" and the like are simply not available in Google Docs, which is my primary use case for this font.
