### ISSUE TITLE
Missing Bold flags for Noto Sans Bold

### ISSUE THREAD

**Issue by moontypespace** [notofonts/latin-greek-cyrillic#384]
## Defect Report
Excuse me for bothering you again, but the style-linking for the Noto-Sans Bold is still not correct.

### Title 
Bold flag in OS/2 and head table are not set.

### Font 
NotoSans-Bold.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSans/NotoSans-Bold.ttf
  >   Date: 2022-03-07

### Font Version
2.007

### OS name and version
Windows 10

### Application name and version
MS Office 365, Word

### Issue
Text is 'Regular', click Bold-button,  text switches to 'Bold Italic', but should switch to 'Bold'.
The 'Bold' bit is not set in the OS/2 and head table.

**Comment by xctvcd** [comment]
Still hoping and waiting for a new release. Or did I miss something? Cheers!

**Comment by simoncozens** [comment]
New releases of Noto Sans should appear here: https://github.com/notofonts/latin-greek-cyrillic/releases

**Comment by xctvcd** [comment]
Hi @simoncozens thanks for the reply. But there seems to be no plain "Noto Sans" there?
