### ISSUE TITLE
Noto Sans (LCG) builds missing from https://github.com/notofonts/notofonts.github.io/tree/main/fonts/

### ISSUE THREAD

**Issue by twardoch** [notofonts/latin-greek-cyrillic#385]
The "NotoSans" folder (and all the builds) are now completely missing from https://github.com/notofonts/notofonts.github.io/tree/main/fonts/ and https://github.com/notofonts/latin-greek-cyrillic/tree/gh-pages/fonts

**Comment by twardoch** [comment]
I see that it’s disabled per https://github.com/notofonts/latin-greek-cyrillic/commit/3a6698cfb2b5e17e6e1c6b5ff4f2df183868ae1b?w=1

**Comment by iwsfutcmd** [comment]
Looks like Noto Sans was re-enabled here: https://github.com/notofonts/latin-greek-cyrillic/commit/9cd692a4d6753db88409161807c5296c954cd8ba

Should we be seeing it returned to the main site soon?

**Comment by simoncozens** [comment]
When there's a new release. There's a slight niggle here in that for horrible historical reasons the "googlefonts" build of Noto Sans needs to include Devanagari.

**Comment by simoncozens** [comment]
This is fixed, kind of; the font is now there, but the Devanagari subset is not shaping correctly.
