### ISSUE TITLE
Suggestion: "YOPQ" axis in Noto Sans sources

### ISSUE THREAD

**Issue by twardoch** [notofonts/latin-greek-cyrillic#386]
Historically, Noto Sans (LCG) shipped in two separate variants: Noto Sans (intended for text sizes) and Noto Sans Display (intended for large sizes). After merging the sources, the Display masters are variations of the basic masters along an axis that is identified as `YOPQ` ("Thin Stroke"). 

This is largely inadequate. "YOPQ" suggests that the axis changes the horizontal strokes (makes them thinner), but this is not what the font does. The original variation was intended as optical size (`opsz`). `YOPQ` or even `XTRA` has nothing to do with how the Display masters differ from the basic ones. 

The Display masters have smaller counters, smaller sidebearings, and are bolder. This truly is `opsz`, nothing else :)

**Comment by simoncozens** [comment]
We've "fixed" this by deprecating the "Display" variant.
