### ISSUE TITLE
Absense of condensed instances

### ISSUE THREAD

**Issue by zhenlige** [notofonts/latin-greek-cyrillic#390]
### Title 
Absense of condensed instances

### Font 
NotoSans[wdth,wght].ttf, NotoSans-Italic[wdth,wght].ttf, NotoSerif[wdth,wght].ttf, NotoSerif-Italic[wdth,wght].ttf, NotoSansMono[wdth,wght].ttf (all variable font with `wdth` axes)

### Where the font came from, and when
Site: https://github.com/notofonts/latin-greek-cyrillic/suites/8966965769/artifacts/412312638
Date: 2022-11-18

### Font Version
Noto Sans/Serif: 2.009
Noto Sans Mono: 2.010

### OS name and version
Windows 11 build 22621.819

### Issue
Although there are `wdth` axes in the variable fonts, there are no “Condensed”, “SemiCondensed” or “ExtraCondensed” instances. It means that one cannot use the condensed versions in a software without the support of variable font configuration.

**Comment by simoncozens** [comment]
We produce multiple sets of artefacts; some for Google Fonts, and some for general use. The versions for Google Fonts are limited in their instances to those that GF accepts, but the general use ones do have a full set of instances. Please see https://notofonts.github.io/latin-greek-cyrillic/
