### ISSUE TITLE
Add Kyrgyzstani som sign ⃀ (U+20C0)

### ISSUE THREAD

**Issue by agusbou2018** [notofonts/latin-greek-cyrillic#391]
Please add the Kyrgyzstani som sign ⃀ (U+20C0) to all Noto LGC fonts.

**Comment by simoncozens** [comment]
Thank you for the report. This is on my list of missing glyphs, so we will do this. As I understand it, the som symbol is Cyrillic letter es with underbar; this should not be too hard to add.

**Comment by Mercury13** [comment]
What if I make an SVG and put it here?
