### ISSUE TITLE
Kerning issues with ĩ repeated and next to apostrophe and glottal stop.

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/latin-greek-cyrillic#393]
### Issue
Kerning with ĩ repeated and next to apostrophe and glottal stop need more space.
Kikamba, Kikuyu, and Meru languages use this character (ĩ) and would benefit from improved kerning.

### Font 
NotoSans-Regular.ttf
NotoSans-Italic.ttf
NotoSans-Bold.ttf
NotoSans-BoldItalic.ttf
NotoSerif-Regular.ttf
NotoSerif-Italic.ttf
NotoSerif-Bold.ttf
NotoSerif-BoldItalic.ttf

### Where the font came from, and when
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/hinted/ttf/NotoSans-Regular.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/hinted/ttf/NotoSans-Italic.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/hinted/ttf/NotoSans-Bold.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/hinted/ttf/NotoSans-BoldItalic.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSerif/hinted/ttf/NotoSerif-Regular.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSerif/hinted/ttf/NotoSerif-Italic.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSerif/hinted/ttf/NotoSerif-Bold.ttf
Site: https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSerif/hinted/ttf/NotoSerif-BoldItalic.ttf
Date: 2021-01-11

### Font Version
Version 2.009; ttfautohint (v1.8.4.7-5d5b)

### Character data
ĩĩ ʼĩ ’ĩ

### Screenshot
![NotoSans-Regular](https://user-images.githubusercontent.com/122098208/211702040-e0aff6e6-a20e-472a-9c3a-24a9fb20a585.png)
![NotoSans-Italic](https://user-images.githubusercontent.com/122098208/211702039-208ae3e1-c3d1-478d-abab-995faab82517.png)
![NotoSans-Bold](https://user-images.githubusercontent.com/122098208/211702034-1180e8ac-e155-42fd-b9fa-49bb44d6e177.png)
![NotoSans-BoldItalic](https://user-images.githubusercontent.com/122098208/211702036-6a025a58-09b0-443c-8dbd-c163e21281c6.png)
![NotoSerif-Regular](https://user-images.githubusercontent.com/122098208/211702031-68fac3d5-2399-4dcf-bdff-2d5e0bf6f1d9.png)
![NotoSerif-Italic](https://user-images.githubusercontent.com/122098208/211702044-cfbaa6c2-e15d-4e54-9756-f9c0f1671d78.png)
![NotoSerif-Bold](https://user-images.githubusercontent.com/122098208/211702042-ba8bff2a-a4cf-4cc0-b117-f051d8aafc0b.png)
![NotoSerif-BoldItalic](https://user-images.githubusercontent.com/122098208/211702043-4ae41bb4-a17f-4860-8252-252d90ef702e.png)

**Comment by simoncozens** [comment]
Same issue (but with more examples) as #131.
