### ISSUE TITLE
The glyph of φ(U+03C6) in Noto Sans is wrong

### ISSUE THREAD

**Issue by lihaoyu1234** [notofonts/latin-greek-cyrillic#395]
The character φ (phi, U+03C6) appears with a loop in the Unicode standard. But in Noto Sans, it has a stroke going from ascender height to descender height like ϕ (U+03D5).

<img width="535" alt="image" src="https://user-images.githubusercontent.com/50037056/217531639-2399e249-c61f-4676-bdb8-3c1218ac8fca.png">

Font Version: Noto Sans 2.010, Noto Serif 2.009, Cambria 6.99

**Comment by simoncozens** [comment]
This is not a bug; there are different styles of Greek fonts, and the design of glyphs in the Unicode standard code tables is not normative. The looped style works well with serif fonts, the unlooped design is better for Sans. But see also Baskerville, Helvetica, and Palatino as examples of fonts with an unlooped phi.
