### ISSUE TITLE
Minus sign U+2212 too short and looking like hyphen-minus

### ISSUE THREAD

**Issue by mykhal** [notofonts/latin-greek-cyrillic#396]
Several days ago, minus sign (U+2212) started appearing very short on some webs in my system (Arch Linux), like normal hyphen-minus, instead of being the same length (and vertical position) as horizontal bar in "+".

In the following image is hyphen-minus, plus sign, and minus sign (U+002D U+002B U+2212) side by side,  
below compared how it should probably look like, which is in NotoSansMono on my system.

![notosansserif-minussign-bug--vs-notosansmono](https://user-images.githubusercontent.com/5636433/218277888-818f790e-2443-44e6-aba3-dd71460578f3.png)

I've traced the problem to new NotoSans-Regular.ttf (same as current on [here](https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoSans/hinted/ttf/NotoSans-Regular.ttf)), which has a short minus sign, see a screenshot from Fontforge below.

![notosansserif-minussign-bug--fontforge](https://user-images.githubusercontent.com/5636433/218278132-7a76baeb-b5bd-4136-9dc9-eb0f92aa3390.png)

**Comment by simoncozens** [comment]
Noto Sans has always had U+2212 equal to U+002D; I added it [here](https://github.com/googlefonts/noto-source/pull/606) last year. I think what's happened is that your system was previously falling back to another font for that glyph, but now it doesn't.

I agree that the design of minus should change, though.

**Comment by Mercury13** [comment]
Same in Serif. Please change this.

**Comment by mgbales** [comment]
Hi,

I'd like to emphasize this request. We use the serif font in a high-stakes reading environment where a more apparent minus sign glyph is a valuable aid to understanding. It would be a significant benefit to our users if the font were updated accordingly.

**Comment by allefeld** [comment]
I would like to support this.

It's particularly important if Noto is used for math typesetting, which has become possible since Noto Math received a MATH table, and if there are minus signs both in regular text (Noto Sans) and formulas (Noto Math).

The correct glyph can be copied from Noto Math:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/1738353/016fccfa-5bcd-4fd1-8e28-f32c98fde060)
(HYPHEN-MINUS, PLUS SIGN, MINUS SIGN)

**Comment by DLasher106** [comment]
Please note that the full versions of the other Noto fonts get their Latin Core characters from the LGC Sans or Serif fonts, so the vast majority of them currently have the wrong U+2212 also.

**Comment by DLasher106** [comment]
And the[ FontBakery warnings](https://notofonts.github.io/latin-greek-cyrillic/fontbakery/notofonts-NotoSerif-googlefonts-report.html) appear to be correct: The Serif Roman minus is a bit too wide, while Serif Italic seems not to have been fixed at all.
