### ISSUE TITLE
Design inconsistency between ʩ (U+02A9) and 𝼀 (U+1DF00)

### ISSUE THREAD

**Issue by Buernia** [notofonts/latin-greek-cyrillic#408]
NotoSans-Italic 2.011
<img width="114" alt="截屏2023-03-30 13 58 26" src="https://user-images.githubusercontent.com/11886946/228743099-b7442740-2d7f-4d05-b1b2-8076df342e7d.png">

NotoSerif-Regular 2.010
<img width="120" alt="截屏2023-03-30 14 01 18" src="https://user-images.githubusercontent.com/11886946/228743586-f17508be-7b59-4b6a-a704-566979ea261e.png">

NotoSerif-Italic 2.010
<img width="116" alt="截屏2023-03-30 14 01 29" src="https://user-images.githubusercontent.com/11886946/228743619-60b129da-e76b-4b76-975e-a27f7f808a7d.png">

NotoSansMono-Regular 2.011
<img width="118" alt="截屏2023-03-30 14 05 01" src="https://user-images.githubusercontent.com/11886946/228744203-e5e061ca-b442-4d8d-ab01-7cc6b77b62db.png">

**Comment by simoncozens** [comment]
Fixed in #427
