### ISSUE TITLE
Two obsolete glyphs: amendments to Unicode

### ISSUE THREAD

**Issue by Mercury13** [notofonts/latin-greek-cyrillic#409]
**UPDATE:** While this issue was hanging, someone fixed A798

### Title 
Glyphs A66E, A798, AB5A are obsolete

### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: notofonts.github.io
Date: 2023-03-30

### Font Version
2.010

### OS name and version
All OS

### Application name and version
All apps

### Issue
Wrong glyphs for those characters: A66E, A798, AB5A

### Character data
U+A66E Cyrillic letter Multiocular O
U+A798 Latin capital letter F with stroke **(someone fixed)**
U+AB5A Latin small letter Y with short right leg

### Screenshot
**YOURS**
![изображение](https://user-images.githubusercontent.com/10164882/228944172-3921c77c-e0dc-43ff-a7bb-f525052267b0.png)
![изображение](https://user-images.githubusercontent.com/10164882/228944246-c609edf2-a9df-4c7a-98b3-47bc8cbf778d.png)
![изображение](https://user-images.githubusercontent.com/10164882/228944305-869a8482-460a-4d9d-8db3-7efc4ec580d9.png)

**MINE**
![изображение](https://user-images.githubusercontent.com/10164882/228944455-e30fb385-e41a-4512-89da-f6c2ac8c1a61.png)
![изображение](https://user-images.githubusercontent.com/10164882/228944493-0c9749b8-412a-460b-998c-21ebe329af37.png)
![изображение](https://user-images.githubusercontent.com/10164882/228944561-0f4d195d-3c20-4964-9275-8a07b265e4fb.png)

**SOURCES**
Multiocular O
![изображение](https://user-images.githubusercontent.com/10164882/228948160-58f3a5e8-b406-4c4e-8146-955b99c9f0e4.png)

F with stroke
![изображение](https://user-images.githubusercontent.com/10164882/228948066-78d151db-ee29-4990-a331-4b993fa4dcee.png)

Old (straight italic) Y with short leg was just a consequence of italic font; in regular font it should look like normal y.
![изображение](https://user-images.githubusercontent.com/10164882/228946180-cbcf52c7-b4ee-4740-ab22-0d02d1d6c23b.png)

**Comment by Mercury13** [comment]
https://www.unicode.org/L2/L2022/22196-cap-letter-f-with-stroke.pdf
https://www.unicode.org/L2/L2022/22199-small-letter-y-with-short-right-leg.pdf
https://unicode.org/wg2/docs/n5170-multiocular-o.pdf

**Comment by Mercury13** [comment]
1. Capital letter was purely reconstructed.
2. They looked at italic letters.
3. They just drew too few eyes.

**Comment by simoncozens** [comment]
First one is #6.

**Comment by Mercury13** [comment]
Checked 4-month-old TTFs from gh-pages:

Serif straight: A798 OK somehow
AB5A BAD (use italic **y**)
A66E BAD (seven eyes)

Serif italic: A798 OK somehow
AB5A BAD (you’ve chosen other shape of italic **y**)
A66E BAD (still seven eyes)

**Comment by Mercury13** [comment]
Sans straight: same
Sans italic: same, just A66E is italic

**Comment by Mercury13** [comment]
Mono straight: same. Just don’t make 10 eyes in A66E, it’ll be worse

**Comment by Mercury13** [comment]
If you want 10 eyes in Mono, turn them 90°. But seven are also OK.
```
 O
O O
 O
O O
 O
O O
 O
O O
 O
```

**Comment by Mercury13** [comment]
I’ll check sources later.

**Comment by moyogo** [comment]
@Mercury13 nothing has changed except U+A798 so far. I’ve opened #443 for U+AB5A.

**Comment by Mercury13** [comment]
I’m closing this, and moving everything to #6.
