### ISSUE TITLE
Wrong glyphs in Latin F/G

### ISSUE THREAD

**Issue by Mercury13** [notofonts/latin-greek-cyrillic#422]
### Title 
Several glyphs of Latin F/G are wrong

### Font 
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: notofonts.github.io
Date: 2023-04-18

### Font Version
2.011

### OS name and version
All OS

### Application name and version
All apps

### Issue
Wrong glyphs of Latin F/G

### Character data
U+10780 modifier letter Small capital Aa (should be of small-cap size)
U+1078E modifier letter Small reversed E
U+1079F modifier letter Small Lezh with retroflex hook (maybe?)
U+107A7 modifier letter Small turned R with long leg and retroflex hook (maybe?)
U+1DF00 Latin small letter Feng digraph with trill
U+1DF01 Latin small letter Reversed script G
U+1DF05 Latin small letter Lezh with retroflex hook (maybe?)
U+1DF08 Latin small letter Turned R with long leg and retroflex hook (maybe?)
U+1DF09 Latin small letter T with hook and retroflex hook
U+1DF0F Latin letter Stretched C with curl (should protrude down rather than up)

### Screenshot
![изображение](https://user-images.githubusercontent.com/10164882/232902878-12ddb3ab-9a20-4264-9c7f-f9be75fb8d7b.png)
![изображение](https://user-images.githubusercontent.com/10164882/232902943-595fe232-7cd9-4af7-982b-1465585559be.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903060-c948eb06-820d-4e39-a60d-67248ce2bd0e.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903086-f3b160dd-4b97-498a-a7fd-bc2a56a9da2b.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903168-0c949e4c-20f6-4bff-98cb-ab029a153681.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903202-5424836a-9223-4920-abff-70b4db261e2d.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903381-5b8acaf3-775c-40e9-aad1-4abd46afcc2d.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903412-d915147a-88d4-412e-aba1-9a7a7558b05e.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903511-127065e9-c680-45fc-9818-07f5ae6cfa3f.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903530-14be72df-d2ea-487a-a4ef-1b25e6b2e547.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903658-01d392e3-576b-4708-874b-3fc8f0a747cf.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903703-46bb89ec-829c-4257-9a6b-af010b92e932.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903811-267202f8-baad-4257-9bb4-1230c5c7f1a9.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903837-67c3570e-5126-41b1-822f-220128a19d4b.png)
![изображение](https://user-images.githubusercontent.com/10164882/232903870-9f503c4d-925d-4f06-9446-b635289df6ae.png)

(here’s 1DF09 from BabelStone Roman)
![изображение](https://user-images.githubusercontent.com/10164882/232904684-a5c4ee08-b534-4ec1-a226-f60542eb0bce.png)

**Comment by Mercury13** [comment]
Here’s my 1DF09, but it’s just a mixture of Noto’s 0288 and 01AD. So you’ll possibly need to revamp these letters too.
![изображение](https://user-images.githubusercontent.com/10164882/232911461-a7777e9a-8d3b-4ffe-8b4d-d1e64e8529f0.png)

**Comment by Buernia** [comment]
U+1DF00 is reported in #408 .

**Comment by moyogo** [comment]
Hmm, I had a fix for a couple of those in a previous branch but missed them out for some reason when doing the Unicode 14 PR after it was impossible to rebase. I'll open a PR with a fix.
