### ISSUE TITLE
Make consistent HOOK and fullwidth RETROFLEX HOOK

### ISSUE THREAD

**Issue by Mercury13** [notofonts/latin-greek-cyrillic#423]
### Title 
HOOK and fullwidth RETROFLEX HOOK are not consistent

### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: notofonts.github.io
Date: 2023-04-18

### Font Version
2.011

### OS name and version
All OS

### Application name and version
All apps

### Issue
Inclusion of U14 into Serif led to an interesting thing.
Fullwidth retroflex hook (01AE)
![изображение](https://user-images.githubusercontent.com/10164882/232913740-7d686cb7-0dc5-4e1b-bf6c-20a162d93b05.png)

Smaller retroflex hook (1D8F)
![изображение](https://user-images.githubusercontent.com/10164882/232913894-ebc41817-d9fb-481c-ba4e-2ed8ab02d4aa.png)

Because of big hook’s bland look, you decided to include a small hook into 1DF08, despite sample image showing big hook.
![изображение](https://user-images.githubusercontent.com/10164882/232914085-0b707017-e1a4-41ab-8363-9e0e64539550.png)

Here’s Cambria’s retroflex hook
![изображение](https://user-images.githubusercontent.com/10164882/232914309-59cc6642-7516-4a81-84e3-7ea246a393df.png)

Same for normal hook. Here’s your 0199
![изображение](https://user-images.githubusercontent.com/10164882/232914558-089dc5be-981e-4336-bfe8-185e37e2cc6d.png)

And here’s 01AD
![изображение](https://user-images.githubusercontent.com/10164882/232914717-fd2ad1e7-15db-42da-aa73-4cceb935dc0f.png)

And this is Cambria’s 01AD
![изображение](https://user-images.githubusercontent.com/10164882/232914965-f9a46a8d-40f1-42c3-9eee-b7e6810c9c27.png)

So you check all HOOKs and RETROFLEX HOOKs, and make them consistent.

**Comment by moyogo** [comment]
Not all hooks should be consistent, the hook ending stems and the hooks attached on the side of stems are often different. Even within one style of hook, optical adjustments are desired. That said #419 needs fixing.
