### ISSUE TITLE
Replacement character not rendering correctly in Photoshop

### ISSUE THREAD

**Issue by curya** [notofonts/latin-greek-cyrillic#430]
### Font 
NotoSans[wdth,wght].ttf
NotoSerif[wdth,wght].ttf
NotoSansMono[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSans-v2.012/NotoSans-v2.012.zip
https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSerif-v2.012/NotoSerif-v2.012.zip
https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSansMono-v2.013/NotoSansMono-v2.013.zip

### Font Version
Not Sans 2.012
Noto Serif 2.012
Noto Mono 2.013

### OS name and version
Windows 10

### Application name and version
Photoshop 24.5

### Issue
The replacement character" is not rendering correctly in Photoshop. It comes out looking like this:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/db0e9120-5916-4f61-9b87-54b757f23aa2)
But strangely, it *does* render correctly in Photoshop's Glyph tab:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/02600e08-fe83-4842-9fd3-0a49d79d89ba)

  1. Type replacement character: �
  2. Photoshop displays it incorrectly

### Character data
�

### Other info
Crowbar shows it correctly:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/8b3db8c2-be61-44fb-9ed4-9fbfd52429e5)

**Comment by simoncozens** [comment]
I'm not sure there's anything wrong with the font. Is this a Photoshop issue?

**Comment by curya** [comment]
I have no idea. It's extremely strange that it renders correctly in the Glyphs tab but not on the document itself. Might have to ask Adobe what's going on here...

**Comment by simoncozens** [comment]
Not my bug, I think, unless I have evidence otherwise...
