### ISSUE TITLE
J inconsistencies and stylistic choices

### ISSUE THREAD

**Issue by curya** [notofonts/latin-greek-cyrillic#435]
### Font 
Noto Sans
Noto Serif
Noto Sans JP
Noto Serif JP

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic
https://github.com/notofonts/noto-cjk

### Font Version
Noto Sans 2.012
Not Serif 2.012
Noto Sans JP 2.004
Noto Serif JP 2.001

### OS name and version
Windows 10

### Issue
Noto Sans and Noto Serif on the left
Noto Sans JP and Noto Serif JP on the right
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/3e55b1d8-5120-4178-baa1-1ca7fdfc4db8)

This has been bugging me for a while now, but since I did not study typography, take everything I say here with a grain of salt.

The tail on both the capital and lowercase J is so tiny. In Noto Sans, it's not such a big deal. The capital I has little serifs which greatly differentiate it which I love very much. Please never get rid of the capital I serifs in Noto Sans. I hate fonts that make the capital I just a line because that makes it almost impossible to tell it apart from a lowercase L. Either way, that's the tiniest tail I've ever seen on a J or j.

But the real problem is with Noto Serif.  A capital J could easily be confused with a capital I when reading with a smaller font size. I'm curious why such a small tail was chosen in the first place.

And strangely, I've noticed in Noto Sans JP, the tail is clearly much larger for the capital J, yet the lowercase j remains the same. The capital J tail is much better here in my opinion, but still looks a little strange. Not enough of a curve upwards...

Then there's the J/j in Noto Serif JP which I don't even know what happened there. There's even less of a tail there than Noto Sans/Serif!

From my amateur viewpoint it seems that whoever made this design choice wanted to prioritize the J's tail being able to go underneath the previous letter. Whether that's a valid concern, I can't say.

But what I *can* say is I very much dislike the tiny tails. Hopefully this post can lead to some discussion on this issue.

----

Also a similar problem with the capital letter Q. It's not as bad as the J issue, but almost every capital Q I've ever seen has had the tail go *through* the bowl. And even worse, the tail in Noto Serif is coming out of the bottom middle???? Why?

----
EDIT: It seems that the J is basically using a reverse tail of a t.
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/5ebe18f9-3ad2-4755-875b-95ae6e189e6c)
That seems...wrong...

**Comment by moyogo** [comment]
There's nothing fundamentally wrong with J or Q in Noto Sans or Noto Serif. The issues described here are your personal preferences.

The J descends below the baseline and hooks left, the I does not, they are clearly different.

Q has a very common form in this style.

Noto Sans CJK and Noto Serif CJK are not using the same design as other Noto San and Noto Serif fonts, they use a design based on Source Sans and Source Serif.

**Comment by moyogo** [comment]
There's nothing fundamentally wrong with J or Q in Noto Sans or Noto Serif. The issues described here are your personal preferences.

The J descends below the baseline and hooks left, the I does not, they are clearly different.

Q has a very common form in this style.

You can look at other sans serif and serif fonts to see these are common: https://fonts.google.com/?subset=latin&preview.text=JIjiQ&preview.text_type=custom&noto.script=Latn&category=Serif,Sans+Serif

Noto Sans CJK and Noto Serif CJK are not using the same design as other Noto San and Noto Serif fonts, they use a design based on Source Sans and Source Serif.

**Comment by curya** [comment]
That's what I did before posting this. I looked at other fonts on fonts.google.com.

Obviously there are many font styles and personal preferences, but with Noto being the first font in the world to cover all of Unicode, I feel like the letters should be put on a higher standard. I think that a capital J should have its own proper tail and not just copy off of a lowercase t.

Similarly with the capital Q. I think the more widely accepted version of it should be used in such a widely used font like Noto. Namely the tail going through the bowl and not coming out of the bottom middle.

And on the issue of the J and I being clearly different, could you at a glance tell which one is which in this picture?
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/f79563a6-2d0d-42f7-831d-28146a212f45)
This is a screenshot of 12 pt Noto Serif. If *I* was reading something like this, I probably couldn't tell the difference without stopping and taking a closer look.

Anyway, I doubt I'm the only one with opinions on this issue. That's why I made this post. To see how other people here felt about it.
