### ISSUE TITLE
Clarification: is Serif Display deprecated?

### ISSUE THREAD

**Issue by DLasher106** [notofonts/latin-greek-cyrillic#436]
I know that Sans Display has been deprecated and tossed in the bin, but is Serif Display also deprecated, or just active-but-quiet?

Noto Serif Display v2.009 is listed under `Releases` here, and the files are listed on the `Dashboard` page. However, the files have not been updated since last year, and they are not listed on the `Development Builds` page (https://notofonts.github.io/latin-greek-cyrillic/).

**Comment by verdy-p** [comment]
Sans Display and Serif Display were defined for usability, i.e. better readability and easier intergration on UI for use on devices with small displays (most of them mobile). Even if most mobile devices now use HiDPI displays, usability remains a valid issue for many users.

"Display" versions are notably tuned to work well with touch screens, so they will allow scripts with complex glyphs to be rendered at larger sizes, while still allowing to work well in multilingual texts using multiple scripts side by side on the same rows of text (this means notably that Latin/Greek/Cyrillic/Deseret/Cherokee/... may need to have larger default line-heights, to fit well beside other Asian scripts that should also be readable, notably CJK, Myanmar, Tibetan; and that scripts that are generally hard to read at small sizes, like Arabic, may be also using larger glyph heights and widths, or will adapt the metrics of base letters to better fit their upper or lower diacritics).

**Comment by moyogo** [comment]
> I know that Sans Display has been deprecated and tossed in the bin, but is Serif Display also deprecated, or just active-but-quiet?

They will not be worked on until further notice. You can consider them to be deprecated.

**Comment by simoncozens** [comment]
> Sans Display and Serif Display were defined for usability

I'm not sure they were, though; that's the problem. The "display" version was not exactly optical size and not exactly contrast, and was a different implementation between serif and sans. It didn't really fit into any of the models of font variation that we support elsewhere. So they need re-thinking, harmonising, and re-drawing.

> You can consider them to be deprecated.

To be honest, I think that's a mild way to describe it.
