### ISSUE TITLE
ss04 not available in Noto Serif

### ISSUE THREAD

**Issue by brunood1** [notofonts/latin-greek-cyrillic#437]
The stylistic set 04 (non-descending uppercase J) that is available in Noto Sans is not available in Noto Serif
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/97195236/04574f75-54c5-4d65-b4c6-306ac09f8bbc)

**Comment by berrymot** [comment]
(now I'm wondering what ss06 does)

**Comment by simoncozens** [comment]
> The stylistic set 04 (non-descending uppercase J) that is available in Noto Sans is not available in Noto Serif

This is a duplicate of #120.

> (now I'm wondering what ss06 does)

Accented Greek small capitals
