### ISSUE TITLE
Problem with the Swedish letters åäö and letters as á, â (diacritical marks) in Excel 

### ISSUE THREAD

**Issue by SusLin77** [notofonts/latin-greek-cyrillic#439]
### Problem with the Swedish letters åäö and letters as á, â (diacritical marks) in Excel 

**Noto Sans**
Family:
NotoSans-Regular.ttf
NotoSans-Light.ttf
NotoSans-LightItalic.ttf
NotoSans-SemiBold.ttf
NotoSans-SemiBoldItalic.ttf
NotoSans-Bold.ttf
NotoSans-BoldItalic.ttf
NotoSans-Italic.ttf

[Noto_Sans_till_Office.zip](https://github.com/notofonts/latin-greek-cyrillic/files/12369738/Noto_Sans_till_Office.zip)

### Where the font came from, and when
  >   Site: https://fonts.google.com/noto/specimen/Noto+Sans/tester?query=Noto+Sans&sort=alpha
  >   Date: 2022-09-30

### Font Version
2007-02-27

### OS name and version
  >Windows 10 ver21 H2

### Application name and version
  > Microsoft Excel 2019

### Issue
  > When using Noto Sans in Excel, the position in the cell is shifted when åäö (a and o with dots over) or letters like á is included in the text. This means that the text placement differ between cells even though the settings are the same. Se screenshot below.

  1. Steps to reproduce: Write in Excel with åäö or letters like á, â,  to se the problem. 
  2. Observed results: Diffrent behavior in cells. Looks really bad. 
  3. Expected results: 
  4. Additional information: Same settings is used for alignement in cells. Comparison with other fonts, for example Arial shows that the problem is with Noto. Se attached screenshot.

### Screenshot from Microsoft Excel

![Noto problem Excel](https://github.com/notofonts/latin-greek-cyrillic/assets/28573379/9f4145ea-9f47-4bc3-9980-2b6a090731d8)

### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by moyogo** [comment]
This is a bug in Excel which uses different font metrics depending on whether the characters used in a cell are only in one specific legacy Windows encoding or not.

**Comment by SusLin77** [comment]
Thank you so much! This helped us understand the and try different things. Ver 2012 seems to be working alright with Excel.
