### ISSUE TITLE
Unicode 15.1 updates

### ISSUE THREAD

**Issue by simoncozens** [notofonts/latin-greek-cyrillic#442]
Unicode 15.1 brought updates to the representative glyphs of U+A798 (F stroke) and U+AB58 (LATIN SMALL LETTER Y WITH SHORT RIGHT LEG). We should check why and determine if our glyphs need updating.

**Comment by Mercury13** [comment]
See my #409, I already checked what needs update due to glyph change.

**Comment by Mercury13** [comment]
AB5A instead of AB58.

**Comment by simoncozens** [comment]
Good point, thanks; let's -> #409.
