### ISSUE TITLE
Variable fonts with OTS Errors

### ISSUE THREAD

**Issue by moontypespace** [notofonts/latin-greek-cyrillic#445]
### Variable fonts with OTS Errors
OT Sanitizer errors via fontbakery report.

### Font 
Fonts stored here: https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/googlefonts/variable-ttf

### Font Version
Version 2.012

### Issue
fontbakery reports ots-sanitize errors.

### Screenshot
<img width="1038" alt="Screenshot 2023-09-15 at 14 49 25" src="https://github.com/notofonts/latin-greek-cyrillic/assets/21055547/e73f129e-fea3-43a1-8e7a-eac10e8733fa">

**Comment by simoncozens** [comment]
Yes, this is known - and unfortunately it's an ots bug. [Null values are allowed in GPOS subtables](https://github.com/khaledhosny/ots/issues/172) (and ots shouldn't be checking GPOS subtables anyway).
