### ISSUE TITLE
Noto Sans "not equal to" (≠) rendering appears broken

### ISSUE THREAD

**Issue by trbabb** [notofonts/latin-greek-cyrillic#448]
## Summary

The "not equal to" glyph (≠) appears broken in all styles of Noto Sans. It looks like the typesetting takes the "equals sign" glyph and overlays a slash glyph on top of it, but the slash is misaligned and offset.

<img width="392" alt="image" src="https://github.com/notofonts/latin-greek-cyrillic/assets/5055969/b586fc24-30da-4b0c-8516-a4074a78ff74">

This applies in `NotoSans-Light.ttf`, as well as all the other weights that I've tried. This remains true after downloading the latest font from [Google Fonts](https://fonts.google.com/noto/specimen/Noto+Sans?preview.size=18&preview.text=burger%20%E2%89%A0%20fries) directly; and it's also visible in Google Fonts "specimen" previewer directly.

### Where the font came from, and when
- From [Google Fonts](https://fonts.google.com/noto/specimen/Noto+Sans?preview.size=18&preview.text=burger%20%E2%89%A0%20fries)
- On 2023-10-14

### Font Version
- 2.007

### Application name and version
- Observed results from typesetting with Harfbuzz; the same result can be seen in Google's own previewer.

### Issue
  > Summarize the issue briefly -- one paragraph preferred

  1. Steps to reproduce
  2. Observed results
  3. Expected results
  4. Additional information 
  > Unicode chart, technical specs, shaping info, comparison with non-Noto fonts, comparison with earlier version of the same font (regression cases)

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by trbabb** [comment]
This was

**Comment by trbabb** [comment]
This was filed by accent before I finished writing it, [here](https://github.com/notofonts/latin-greek-cyrillic/issues/449) is the finished issue.

**Comment by prakashDiana** [comment]
I think it's a canonical decomposition: `equal` + `uni0338`.

**Comment by prakashDiana** [comment]
The width is `572`.
