### ISSUE TITLE
OpenType features do not work in Adobe programs

### ISSUE THREAD

**Issue by curya** [notofonts/latin-greek-cyrillic#450]
### Font 
NotoSans[wdth,wght].ttf
NotoSerif[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases

### Font Version
2.013

### OS name and version
Windows 10

### Application name and version
Adobe Photoshop
Adobe Illustator

### Issue
Only a few features are able to be used in Adobe programs. The rest are grayed out. (See screenshots below.) Stylistic sets, for example, can not be used. This probably affects **all** Noto fonts.

### Steps to reproduce
1. Type something in Photoshop/Illustrator
2. Try enabling OpenType features.

### Screenshot
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/a9af61e5-fc52-451d-8f2a-ebddfa62c146)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/ecbd3787-4d07-4721-b2da-5589d0cad073)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/7bc89ab9-4017-4e85-b7a4-0ec234f5dabd)

**Comment by simoncozens** [comment]
I don't think this is a bug. The greyed out features are greyed out because they do not exist in the font. It's not a great UI decision on Adobe's part, but that's why it's happening. The features you *can* select are fine.

**Comment by curya** [comment]
@simoncozens I'm not an expert on this, but ss04 for example (Titling Alternates I and J for titling and all cap settings) is in fact in this font:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/f7cb1ce3-18a8-46b2-94f4-42885868f9b3)
But it's grayed out in Adobe products.

**Comment by simoncozens** [comment]
I can't fix bugs in Adobe products. :-) Maybe it's being clever - were you selecting any text that contained Is or Js?
