### ISSUE TITLE
U+0361 does not render in Adobe Illustrator

### ISSUE THREAD

**Issue by curya** [notofonts/latin-greek-cyrillic#451]
### Font 
NotoSans[wdth,wght].ttf
NotoSerif[wdth,wght].ttf
NotoSansMono[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases

### Font Version
Noto Sans 2.013
Noto Serif 2.013
Noto Mono 2.014

### OS name and version
Windows 10

### Application name and version
Adobe Illustator 2024

### Issue
This is really strange. It works fine in Photoshop, but doesn't render at all in Illustrator.
I've discovered that I can get it to render if I type U+0361 twice. In which case it is positioned incorrectly.
Also, it seems to be possibly incorrectly positioned in Photoshop as it is not directly center between the two letters.

Even stranger:
Type it into Photoshop. Then copy and paste *that* into Illustrator and it somehow forces the symbol to appear in Illustrator!

  1. Type t͡ʃ in Illustrator and Photoshop
  2. Observe discrepancy

### Character data
U+0361
͡
t͡ʃ

### Screenshot
Illustrator:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/855cd9ec-3f55-46a5-8892-f69d8ecd67f9)

Photoshop:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/805c09e2-c4ef-4268-b2c8-395da855d09e)

Typing U+0361 twice in Illustrator (incorrectly positioned):
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/7e725807-cdeb-4e61-a28e-bd166b22e247)

**Comment by simoncozens** [comment]
I'm not terribly surprised; Adobe's support for OpenType is not what it should be. But this feels like an Adobe bug, not a font bug - you should file it with Adobe.

**Comment by curya** [comment]
@simoncozens I'm a little confused as to what it's actually *supposed* to look like.

Here's crowbar:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/928ac9bc-d42f-4e32-ba16-f2ada8b00db0)

And here's powerpoint:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/22cbe8e1-aa39-4f58-90be-af5d553d5704)

Which one is the correct positioning?
