### ISSUE TITLE
Kerning inconsistent for decimal numbers '.'

### ISSUE THREAD

**Issue by tysonmatanich** [notofonts/latin-greek-cyrillic#461]
Kerning seems inconsistent for '.' decimal numbers. The space is noticeably more between '.1'

Tested using Google Fonts website https://fonts.google.com/noto/specimen/Noto+Sans/tester
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/2696475/e8bdf9df-5454-4d91-be0e-6ba6e7b8bb15)

> 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9

**Comment by simoncozens** [comment]
This isn't a bug - Noto Sans uses tabular figures by default. In an opentype environment you can turn on the `lnum` (Lining Numerals) feature to get lining numerals.
