### ISSUE TITLE
Issue with Noto Sans Display glyph "Ç"

### ISSUE THREAD

**Issue by chrissimpkins** [notofonts/latin-greek-cyrillic#462]
Anonymous user report from the fonts.google.com front end:

URL: https://fonts.google.com/noto/specimen/Noto+Sans+Display

Hi.

In the Noto Sans Display typeface, the glyphs "Ç" and in the "ç" the diacritic is positioned too far to the right. This becomes more noticeable from semibold weight upwards.

Please see this example: https://fonts.google.com/noto/specimen/Noto+Sans+Display?category=Sans+Serif&sort=date&preview.text=Gradua%C3%A7%C3%A3o&preview.text_type=custom

Thanks in advance.

**Comment by simoncozens** [comment]
Noto Sans Display is kinda deprecated now; we don't maintain that font any more - we've got rid of the sources from this repository. So there's no fix here.
