### ISSUE TITLE
add 1df25..a

### ISSUE THREAD

**Issue by berrymot** [notofonts/latin-greek-cyrillic#468]
Somehow these didn't make it into the Unicode 15.0 update. Discovered by running [this](https://github.com/berrymot/notoize) (with line 246 of src/lib.rs uncommented; this fetches the fonts from `raw.githubusercontent.com` so they're the most recent version) on the string "𝼥𝼦𝼧𝼨𝼩𝼪":

![image](https://github.com/notofonts/latin-greek-cyrillic/assets/50974538/7255748f-9401-412b-a177-63b5d761dd62)

character data:
> U+1DF25 : LATIN SMALL LETTER D WITH MID-HEIGHT LEFT HOOK
U+1DF26 : LATIN SMALL LETTER L WITH MID-HEIGHT LEFT HOOK
U+1DF27 : LATIN SMALL LETTER N WITH MID-HEIGHT LEFT HOOK
U+1DF28 : LATIN SMALL LETTER R WITH MID-HEIGHT LEFT HOOK
U+1DF29 : LATIN SMALL LETTER S WITH MID-HEIGHT LEFT HOOK
U+1DF2A : LATIN SMALL LETTER T WITH MID-HEIGHT LEFT HOOK

**Comment by aelatham** [comment]
Note that 6 characters introduced in 14.0 are also missing: U+1AC1, U+1AC2, U+1AC3, U+1AC4, U+1AC6, and U+1DFA.

**Comment by simoncozens** [comment]
Thanks for reporting this, but please be aware we already track missing characters in Noto separately at https://notofonts.github.io/overview/gaplist.txt

We are aware of them and will get around to them when time and resources allow.
