### ISSUE TITLE
Add U+1DFA

### ISSUE THREAD

**Issue by aelatham** [notofonts/latin-greek-cyrillic#470]
U+1DFA is already in the Noto Sans Syriac beta. Is it possible to import U+1DFA into these fonts, or are the fonts too different?

**Comment by moyogo** [comment]
It's script is "Inherited" so it could work. What's the use case?

**Comment by aelatham** [comment]
See https://www.unicode.org/L2/L2020/20019-syriac-dot-below-left.pdf

**Comment by simoncozens** [comment]
Is it *actually* used for the Romanization of Syriac? Do you have examples of what it looks like? I'm unclear why you want this, and I'm wary of adding more and more Common script characters to additional fonts (and all the anchors to support them) - it just makes everything heavier for everyone, for very marginal gain.

**Comment by aelatham** [comment]
I see no confirmation of any Latin usage.
