### ISSUE TITLE
no full/ for Sans Mono

### ISSUE THREAD

**Issue by berrymot** [notofonts/latin-greek-cyrillic#471]

**Comment by simoncozens** [comment]
Full means "we added a Latin core". But this is already a Latin font, so no full build is needed.

**Comment by berrymot** [comment]
wait then why *do* Sans and Serif have full/s?

**Comment by simoncozens** [comment]
Serif does not have a full build. Sans has a full build for messy historic reasons.

Once upon a time when Google Docs/Workspace was young, they requested Noto Sans but they also wanted it to work seamlessly with documents in Hindi without people needing to change fonts, so they asked for the version of Noto Sans in Google Fonts to contain a Devanagari glyphset. Now Workspace's support for other languages is better but once you've released a font with some glyphs in it, documents will break if you take them out, so it's got to stay. So for the exceptional case of Noto Sans, "full"/"googlefonts" builds mean "we added a Devanagari core".

**Comment by berrymot** [comment]
ahh i see
