### ISSUE TITLE
-> symbols don't align very well

### ISSUE THREAD

**Issue by stepanbujnak** [notofonts/latin-greek-cyrillic#472]
Some programming languages use symbols `->` for pointer dereference (C++, Go, ...) and Noto Sans Mono doesn't align them very well so the "arrow" looks crooked.

This is a picture of Noto Sans Mono
<img width="39" alt="Screenshot 2024-04-18 at 10 33 10" src="https://github.com/notofonts/latin-greek-cyrillic/assets/355614/75f67171-2998-4fef-821f-831e06b38ab9">

And here's a picture of an alternative monospaced font:
<img width="38" alt="Screenshot 2024-04-18 at 10 33 33" src="https://github.com/notofonts/latin-greek-cyrillic/assets/355614/61992a2e-163c-4fa7-a82b-a9623a9970df">

Would it be possible to change the `-` character to be aligned with the `>` character? Thank you.

**Comment by simoncozens** [comment]
This is a tricky one; the hyphen is actually well aligned for text, but not against mathematical symbols. (The *minus* is of course aligned well against mathematical symbols)

![shape](https://github.com/notofonts/latin-greek-cyrillic/assets/106728/62899f7f-ef48-4b11-9ec8-f21017f78906)

I don't want to change the alignment in a way that would make the `a-e` case worse. We could contextually swap it for a minus before/after certain punctuation, but that way lies madness.

I think it's reasonable to say that some monospace fonts are good for coding and others aren't, and fonts shouldn't try to do everything.

**Comment by dm-u** [comment]
What arguments might exist against aligning all mathematical symbols to the height of lowercase letters?

![Screenshot 2024-04-26 105441](https://github.com/notofonts/latin-greek-cyrillic/assets/1056017/3c3c85fd-f823-4ecf-862e-bb303eaa492d)

**Comment by simoncozens** [comment]
I just changed the minus glyph for one that aligns with plus, so everything should be aligned now.
