### ISSUE TITLE
R can overlap the next letter

### ISSUE THREAD

**Issue by MAZ06** [notofonts/latin-greek-cyrillic#478]
### Font 
NotoSans[wdth,wght].ttf
NotoSerif[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases

### Font Version
Noto Sans 2.013
Noto Serif 2.013

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
Sans:
It looks like R starts touching A in the Bold weight and then starts overlapping in heavier weights of Noto Sans.

Happens to a slightly less extent with R and X (including lowercase x). 

Serif:
Strangely, Noto Serif has an opposite issue. R plus lowercase x in lighter weights has the overlap issue. Same for R and X. Though R and X are still pretty close even in heavier weights.

R and A and in Noto Serif have the issue in all weights it seems.

The serif issues here are probably related to my other post: #474.

### Character data
R
A
X

### Screenshot
Regular
SemiBold
Bold
ExtraBold
Black
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/c69833d1-5005-4af9-8587-32843965e35a)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/c0cb79e9-7c2e-4973-b3fa-afbb92c48d62)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/7f0b9266-63e4-492e-a70d-3e0dbbcd35f0)

Thin
Extra Light
Light
Regular
Medium
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/9a65af21-28ce-457d-a5e3-ebd8e5d7663b)

![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/cb4ec316-8130-4f6d-b522-d7dd620db278)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/330130ef-e207-42c6-b251-5996a6843a7a)

**Comment by MAZ06** [comment]
Also happens with Cyrillic:
АЯ
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/bb522659-acc6-45f5-9ba6-d8171357ffe0)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/78e5ed99-2ffb-4997-b4f4-229428d20336)

ЖЯ
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/01bc1b63-e9f3-4581-805d-f6d2f2a96b12)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/5daf5ddd-983c-4a60-9b42-8fe48f25874e)

**Comment by berrymot** [comment]
i'm not sure how problematic this is; fixing it might make the character spacing look worse

**Comment by MAZ06** [comment]
@berrymot I think this is a small part of a larger issue which I showed off in my other post about Noto Serif. It just so happens that I found the first part of this specific issue when using Noto Sans.

**Comment by simoncozens** [comment]
Are you assuming that an overlap is intrinsically bad? I'm not convinced that it is.

**Comment by MAZ06** [comment]
@simoncozens Is there a situation where overlap is good?

Compare R and A to K and A in the Black weight:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/9af797d5-3df4-42a4-8e6e-a021dc599ee9)
The K and A touch but don't overlap.

**Comment by simoncozens** [comment]
>  Is there a situation where overlap is good?

Yes, plenty, if it helps the overall rhythm of the top half of the letter. I suggest looking at a number of other serif fonts to see how they do it. The overlap you are complaining about is not at all uncommon.

<img width="264" alt="Screenshot 2024-05-17 at 21 33 59" src="https://github.com/notofonts/latin-greek-cyrillic/assets/106728/e9ea8d21-b639-475c-9636-7091bd0a1f21">

There isn't a bug in this font - there's just something you don't like about it, which is a different thing. Other fonts are available.

**Comment by MAZ06** [comment]
@simoncozens Well, first of all, the example you posted here is Serif. It's one thing for the serifs of letters to touch, but should the sans letters themselves touch?

And secondly, the serifs don't even connect correctly as seen here in one of my previous screenshots:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/043a9f13-2389-4699-8617-39dd59e3a1a9)
