### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by aelatham** [notofonts/latin-greek-cyrillic#480]
See #32, #229, #233, #468, #469, and #483.

Not covered by other fonts:
*Missing characters added in 14.0 at 1AC1-1AC4 and 1AC6
*New Unicode 15.0 characters at 1DF25-1DF2A and the entire Cyrillic Extended-D block.

Covered by other fonts, but still requested by others:
*Arrows at 2190-2195 and 21A8 (no longer in Sans/Serif)
*U+2212 (no longer in Sans/Serif)
*U+2202, U+2206, U+220F, U+2211, U+2215, U+2219, U+221A, U+221E, U+222B, U+2248, U+2260, U+2264, U+2265, U+25CA (Mac OS Roman characters no longer in Sans/Serif)
*Musical notes at 266A and 266B
*U+2A7D and U+2A7E (Noto Mono only)

**Comment by simoncozens** [comment]
There's no reason for the "requested" characters to be in this font. Noto Sans is not expected to cover all of Unicode, and is meant to be used in a fallback stack. Other fonts in the Noto collection cover these characters.

You don't need to create issues which duplicate other issues.

**Comment by aelatham** [comment]
I was inspired by issue #69 from Noto Sans Symbols.

**Comment by nataliakeniganti** [comment]
Lets go
