### ISSUE TITLE
G Kerning

### ISSUE THREAD

**Issue by MAZ06** [notofonts/latin-greek-cyrillic#481]
### Font 
NotoSans[wdth,wght].ttf
NotoSerif[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases

### Font Version
Noto Sans 2.013
Noto Serif 2.013

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
If a G is preceded by a letter with a flat right edge, there seems to be too much space. This is especially noticeable when changing the vertical tracking.

For some reason, this also applies if the preceding letter is O.

### Screenshot
![image](https://github.com/user-attachments/assets/3bf5be07-a21f-4356-a356-1ec7fbdd5e8c)
![image](https://github.com/user-attachments/assets/fc3c6aa7-f207-4337-9967-37e2ae89a793)
![image](https://github.com/user-attachments/assets/743341a4-2e5d-42a4-a55a-86bd2f667433)
![image](https://github.com/user-attachments/assets/8f35c3ea-7a46-4e15-9dad-ed162604255f)
![image](https://github.com/user-attachments/assets/9527e99c-8894-4ed9-8f3f-1cfbc0ebc197)
![image](https://github.com/user-attachments/assets/7a50f5a0-0274-4345-aaaf-49ee17dfaecf)

**Comment by simoncozens** [comment]
> This is especially noticeable when changing the vertical tracking.

Changing tracking disables kerning, which is why it looks wrong.

**Comment by MAZ06** [comment]
@simoncozens It's still noticeably there even with normal tracking...
