### ISSUE TITLE
Missing minus sign (U+2212) 

### ISSUE THREAD

**Issue by jamal-ali1989** [notofonts/latin-greek-cyrillic#483]
### Title 
Noto Sans, Noto Sans Display, Noto Serif, Noto Serif Display fonts are missing the minus sign "−" (Unicode sign U+2212). This is not a hyphen, n-dash, m-dash or a hyphen-minus

### Font 
 All aforementioned Noto fonts — Noto Sans, Noto Sans Display, Noto Serif, Noto Serif Display
 You can upload the problem font here unless it is a Chinese, Japanese or Korean font (these are large).

### Where the font came from, and when
Noto fonts that came pre-installed with Linux Mint Cinnamon 22(Ubuntu-based)

### Font Version
Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.

### OS name and version
Linux Mint Cinnamon 22. However It did persist in previous versions well.

**Comment by simoncozens** [comment]
There's no reason for the character to be in this font. Noto Sans is not expected to cover all of Unicode, and is meant to be used in a fallback stack. Other fonts in the Noto collection cover this character.

**Comment by jamal-ali1989** [comment]
Does that mean that if I use this missing character, instead of showing me the "missing" sign, it will show it from Noto font types that have it?

**Comment by simoncozens** [comment]
That entirely depends on your application.

**Comment by aelatham** [comment]
@jamal-ali1989 Try clicking "Development Builds" on notofonts.github.io and downloading. Noto Serif from there does contain U+2212.

**Comment by jamal-ali1989** [comment]
Thanks for the suggestion. Will this eventually be rolled over to regular builds? I didn't install Noto fonts from github. I am using Linux and I installed the fonts as a package. If these packages eventually get it, I might as well wait.

**Comment by simoncozens** [comment]
Yes, development builds will become the next release.

**Comment by jamal-ali1989** [comment]
Thank you, I guess I will just wait it out then :)
