### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/latin-greek-cyrillic#488]
Hello. Thank you for providing us with great fonts.
I’d like to build this fonts with the latest commit, but it faild.
Is there any workaround?

**Comment by simoncozens** [comment]
It looks like there is a problem with the full builds, specifically the way we are merging anchors between the Devanagari dotted circle and the Latin glyph. It's a bug in ufomerge; I'll try to fix it.

**Comment by YusukeShirakihara** [comment]
"make build" succeeded. Thank you so much!
