### ISSUE TITLE
move ufo2ft filters out of userData into build config options?

### ISSUE THREAD

**Issue by anthrotype** [notofonts/latin-greek-cyrillic#489]
While comparing fontc vs fontmake output on this set of Noto fonts, I noticed the contain things like:

https://github.com/notofonts/latin-greek-cyrillic/blob/54e596e970f96470e42ca481c2c8f17c5f1687a3/sources/NotoSans.glyphspackage/fontinfo.plist#L5662-L5667

which are the result of ufo2glyphs conversion most likely. When fontmake then converts these .glyphspackage sources to master UFOs the userData is stored in the UFO lib and used by ufo2ft to activate the filters on compile.

even though fontc supports flattening components via CLI flag, it doesn't look for these settings at the moment so the ttx diff'ing ends up being skewed, since fontmake silently enables the component flattening wheres fontc does not.

Could these userData settings be removed from the sources and moved into the build config files? Surely gftools or whatever toolchain these noto fonts use, must have options to enable/disable this.

**Comment by simoncozens** [comment]
Yes, that shouldn't be in the source.
