### ISSUE TITLE
`№` should be two characters wide, because it includes two characters.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [notofonts/latin-greek-cyrillic#490]
### Title 

> `№` should be two characters wide, because it includes two characters.

### Font 

Noto Sans Mono

### Where the font came from, and when

https://packages.fedoraproject.org/pkgs/google-noto-fonts/google-noto-sans-mono-fonts/ at +2024-09-08T13:56:39+01:00.

### Font Version

https://kojipkgs.fedoraproject.org//packages/google-noto-fonts/20240301/2.fc40/noarch/google-noto-sans-mono-fonts-20240301-2.fc40.noarch.rpm from https://koji.fedoraproject.org/koji/rpminfo?rpmID=38077645

### OS name and version

https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso

### Application name and version

`code-insiders-1.94.0-1725631051.el8.rpm`, and https://kojipkgs.fedoraproject.org//packages/firefox/130.0/3.fc40/x86_64/firefox-130.0-3.fc40.x86_64.rpm (from https://koji.fedoraproject.org/koji/rpminfo?rpmID=39947457).

### Character data

https://en.wiktionary.org/w/index.php?title=%E2%84%96&oldid=78496634#:~:text=U+2116%2C%20%26%238470;,NUMERO%20SIGN states:

> [`U+2116`](https://util.unicode.org/UnicodeJsps/character.jsp?a=2116), [`&#8470`](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references);

### Screenshot

1.	> ![image](https://github.com/user-attachments/assets/77805496-1323-440f-8c5c-b650430b6211)
1.	> ![image](https://github.com/user-attachments/assets/198cad92-f5b3-4282-8db3-9fa85021a350)

### Harfbuzz hb-view and hb-shape

Ascertaining the path isn't trivial, and I doub that this information is necessary for this. If that's incorrect, notify me and I'll retry.

### Fontview

> Fontview displays the text.

I don't understand what should be placed in this section.

### Fontdiff

> Fontdiff displays the text using two versions of the font side by side.

**Comment by RokeJulianLockhart** [comment]
Perhaps this would have been better filed as an FR. I've done so below:

> #### **Is your feature request related to a problem? Please describe.**
> 
> 
> 
> The "№" symbol displays as one character, which means that it's almost unreadably narrow. This doesn't make much sense, because it's comprised of two characters ("N" and "<sub>ō</sub>").
> 
> #### **Describe the solution you'd like**
> 
> 
> 
> Render it with the width of two monospace characters, since this is perfectly acceptible in a monospace font as it doesn't break the grid.
> 
> #### **Describe alternatives you've considered**
> 
> 
> 
> The current implementation.
> 
> #### **Additional context**
> 
> 
> 
> https://www.reddit.com/r/programming/comments/3kitlm/when_monospace_fonts_arent_the_unicode_character/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button might be interesting, although I expect that this has already been considered.

**Comment by simoncozens** [comment]
It's true that it doesn't break the grid, but double space characters in monospace fonts cause other problems. A character no longer equals an em, which messes up tables, code, etc.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/notofonts/latin-greek-cyrillic/issues/490#issuecomment-2336768083

@simoncozens, so is there a solution for characters like this? I ask because there are surely other, larger UNICODE characters that don't fit into a single Latin character's space, like `௵` or `ဪ` (lots of Asian stuff, like Devanagari and Arabic).

**Comment by simoncozens** [comment]
We don't offer monospace fonts for those scripts, and this is probably a big part of why. :-)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/notofonts/latin-greek-cyrillic/issues/490#issuecomment-2336769225

@simoncozens, perhaps by not doing so, you've avoided tacking the fundamental problem by not tackling its logical extremes, thereby letting smaller characters suffer from this. Would it be wise to re-scope this consequently to include all multi-character characters, or do you just consider the issue unactionable?

**Comment by simoncozens** [comment]
I don't think creating monospace fonts for all of Unicode is a feasible rescoping. It's practically impossible for designers, it wouldn't work technically because of complex shaping, and financially it would be a massive investment for questionable gain. Not going to happen.

In the specific case of Latin, we get complaints both ways - if one glyph stretches over two ems, we get complaints that the monospace font isn't actually monospace (#234), and we get issues like this if it doesn't. So I don't think it's a solveable problem.

**Comment by RokeJulianLockhart** [comment]
> I don't think creating monospace fonts for all of Unicode is a feasible rescoping. It's practically impossible for designers, it wouldn't work technically because of complex shaping, and financially it would be a massive investment for questionable gain. Not going to happen.

@simoncozens, I didn't mean that! I've not the power in this project to do so, nor the interest. I merely referred to re-scoping this issue to include all multi-character glyphs that are *currently* included and *planned* to be.

> In the specific case of Latin, we get complaints both ways - if one glyph stretches over two ems, we get complaints that the monospace font isn't actually monospace (https://github.com/notofonts/latin-greek-cyrillic/issues/234), and we get issues like this if it doesn't. So I don't think it's a solveable problem.

Well, when presented with a dilemma, one has to be chosen. Surely you've chosen a specific option, rather than deciding per-glyph?

**Comment by simoncozens** [comment]
Yes, we're making Mono monospaced, one character per em.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/notofonts/latin-greek-cyrillic/issues/490#issuecomment-2336774710

@simoncozens, even CJK? Usually, they're `2em`, from what I've read.

**Comment by simoncozens** [comment]
> even CJK?

"We're making *Mono* monospaced."

**Comment by RokeJulianLockhart** [comment]
@simoncozens, per https://notofonts.github.io/noto-docs/specimen/NotoSansMonoCJKhk/ to https://notofonts.github.io/noto-docs/specimen/NotoSansMonoCJKtc/, aren't they counterparts to *Mono*? Apologies - your response seems a little confusing.

**Comment by simoncozens** [comment]
We're in the latin-greek-cyrillic repo here, talking about an issue you raised in Noto Sans Mono. And I think I've said all I want to say about that particular issue.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/notofonts/latin-greek-cyrillic/issues/490#issuecomment-2336777826

Thanks.
