### ISSUE TITLE
Add some characters from Unicode 16.0

### ISSUE THREAD

**Issue by berrymot** [notofonts/latin-greek-cyrillic#492]
![image](https://github.com/user-attachments/assets/3e8b08ea-6993-4d22-82a6-92ae0e1cbb13)

![image](https://github.com/user-attachments/assets/8cfb110e-7ad8-44cd-9b34-c62e9239337e)

![image](https://github.com/user-attachments/assets/1e36aeeb-5b6d-4754-9a7e-a948af973f1d)

**Comment by aelatham** [comment]
#468 and my comment cover the 14.0 and 15.0 missing characters.

**Comment by simoncozens** [comment]
Thanks for reporting this, but please be aware we already track missing characters in Noto separately at https://notofonts.github.io/overview/gaplist.txt

We are aware of them and will get around to them when time and resources allow.
