### ISSUE TITLE
GitHub Actions Workflow Failures

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/latin-greek-cyrillic#498]
Hello.
I noticed that the last three workflows in GitHub Actions have failed.

https://github.com/notofonts/latin-greek-cyrillic/actions/runs/11693715773
https://github.com/notofonts/latin-greek-cyrillic/actions/runs/11692925779
https://github.com/notofonts/latin-greek-cyrillic/actions/runs/11692608604

The same thing is happening in my personal environment.
If you have any solutions, please let me know.
Thank you for always doing high-quality work!

**Comment by simoncozens** [comment]
Ooops, recent changes in gftools-builder broke all Noto builds. I think it's time to deprecate `notobuilder`. I'll work on this.

**Comment by simoncozens** [comment]
Fixed now.

**Comment by YusukeShirakihara** [comment]
Fantastic work! I really appreciate it!
