### ISSUE TITLE
Preceding cyrllic letters

### ISSUE THREAD

**Issue by nataliakeniganti** [notofonts/latin-greek-cyrillic#501]
### Font
NotoSerif[wdth,wght].ttf
 
### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases
 
### Font Version
Noto Serif 2.014

### OS name and version
Windows 11
 
### Application name and version
Everything
 
### Issue
Both U+047D, U+038F preceding letter in some cases.

### Character data
Ѽ - U+047D Ҋ - U+048A Ҏ - U+048E
 
### Screenshot
![bandicam 2024-11-17 09-38-34-013](https://github.com/user-attachments/assets/770e35fb-341c-4b1e-8207-7d8d97334d10)

**Comment by Mercury13** [comment]
What are you talking about? Poor kerning?
