### ISSUE TITLE
Incomplete soft-dotting with intervening marks

### ISSUE THREAD

**Issue by dscorbett** [notofonts/latin-greek-cyrillic#64]
### Font
NotoMono-Regular.otf
NotoSans-Regular.ttf
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/bf20559450ec75aec7a646b208343540a4496262/phaseIII_only/unhinted/otf/NotoMono/NotoMono-Regular.otf
Site: https://github.com/googlefonts/noto-fonts/blob/bf20559450ec75aec7a646b208343540a4496262/phaseIII_only/hinted/ttf/NotoSans/NotoSans-Regular.ttf
Site: https://github.com/googlefonts/noto-fonts/blob/bf20559450ec75aec7a646b208343540a4496262/phaseIII_only/hinted/ttf/NotoSerif/NotoSerif-Regular.ttf
Date: 2020-08-01

### Font version
Noto Mono: Version 2.004
Noto Sans: Version 2.003; ttfautohint (v1.8.2)
Noto Serif: Version 2.003; ttfautohint (v1.8.2)

### Issue
Soft dots are removed before a mark above only if there are fewer than two marks not above between the base and the above-base mark. They should be removed regardless of how many marks intervene. The simplest solution is for the lookup that removes soft dots to use a mark set of the above-base marks.

### Character data
i̠̥̽
U+0069 LATIN SMALL LETTER I
U+0320 COMBINING MINUS SIGN BELOW
U+0325 COMBINING RING BELOW
U+033D COMBINING X ABOVE

### Screenshot
![i̠̥̽](https://user-images.githubusercontent.com/1124347/89801944-c9c68380-dafe-11ea-9cdd-cf5b636df458.png)![i̠̥̽](https://user-images.githubusercontent.com/1124347/89801946-c9c68380-dafe-11ea-87e3-284c01a3d303.png)![i̠̥̽](https://user-images.githubusercontent.com/1124347/89801948-c9c68380-dafe-11ea-823e-442c58113b74.png)

**Comment by moyogo** [comment]
@curya What application and what OS is this in?

**Comment by curya** [comment]
@moyogo  Photoshop. Windows 10.

**Comment by moyogo** [comment]
> @moyogo  Photoshop. Windows 10.

In Adobe apps you may have to change the text engine being used.
Have a look at https://helpx.adobe.com/lu_en/photoshop/using/arabic-hebrew.html

**Comment by curya** [comment]
@moyogo It's incorrect in everything. Photoshop is just what I used to show it here.

Noto Sans Medium, for example, works perfectly.

Noto Sans Medium:
![image](https://user-images.githubusercontent.com/71131343/229183225-77d2c5df-8183-4f80-ad07-ff7a2e229415.png)

**Comment by curya** [comment]
@simoncozens Pinging you to make sure you see this. :)

**Comment by simoncozens** [comment]
I see all Noto bug reports. :-)

**Comment by curya** [comment]
This could also be related to this issue?
![image](https://user-images.githubusercontent.com/71131343/232154649-788f75ed-d54f-449b-b31f-1a0c230289fc.png)

**Comment by moyogo** [comment]
@curya Which files are you using exactly? What version and where did you get them? See the orginial issue post above.

**Comment by moyogo** [comment]
@curya Here’s i̠̥̽ẅ́r̢̡ in WordPad with googlefonts/ttf/NotoSans-Regular.ttf from [NotoSans-v2.011.zip](https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSans-v2.011/NotoSans-v2.011.zip). All the other NotoSans-Regular.ttf or .otf and variable font files produce the same result in my test on Windows 11 22621.1413.
<img width="108" alt="Screenshot 2023-04-16 at 05 14 11" src="https://user-images.githubusercontent.com/1923747/232264391-d43667b9-c462-42ac-a989-da5abe436b37.png">
Can you try opening `services.msc` and disable "Windows Fonts Cache", then uninstall and reinstall NotoSans-Regular.ttf (or the one you’re using)?

**Comment by curya** [comment]
@moyogo Sorry for the super late reply here, but I believe you were correct. For some reason, Photoshop installed Noto Sans version 1.*** and it was conflicting with my newer version.
@simoncozens Sorry for the trouble. This was merely user error (Photoshop error?). You can close this issue as fixed.

**Comment by simoncozens** [comment]
Which Photoshop? In older versions of Photoshop, the default shaping engine didn't handle mark-to-mark positioning. At any rate, I don't think there is a problem with the font here; you can test by dropping the font onto [Crowbar](http://corvelsoftware.co.uk/crowbar/) and typing in the text. If the shaping engine in an application doesn't work, that's bad, but it's not something we can fix.

**Comment by HydroHydro** [comment]
@simoncozens Newest Photoshop. Version 24.5
I tried Crowbar and got the same issue:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/43591297/052596c5-aa45-4e94-9022-dd269e0f2846)
Looks like there *is* an issue...

**Comment by curya** [comment]
@simoncozens Newest Photoshop. Version 24.5
I tried Crowbar and got the same issue:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/43591297/052596c5-aa45-4e94-9022-dd269e0f2846)
Looks like there *is* an issue...

**Comment by simoncozens** [comment]
I think the issue is in the version of Noto Sans you're using. Latest from [here](https://notofonts.github.io/latin-greek-cyrillic/):
<img width="878" alt="Screenshot 2023-05-25 at 14 53 19" src="https://github.com/notofonts/latin-greek-cyrillic/assets/106728/1efa3d33-0eba-4766-a95c-27b460c46e62">

**Comment by curya** [comment]
https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSans-v2.012/NotoSans-v2.012.zip
This is the one I was using.

I tried the one you linked and got the exact same result. No idea why we're getting such different outcomes when using the exact same files.

**Comment by curya** [comment]
Update:
Noto Sans 2.011 works correctly!
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/04fdf2ba-a398-4d64-8674-d58ccc3d236b)

Noto Sans 2.012 is where something went wrong:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/d725e0de-13b4-41f3-ac4b-9fc52105be30)

**Comment by curya** [comment]
Update:
Noto Sans 2.011 works correctly!
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/2a659923-02eb-4afa-bb66-35aa44d039f5)

Noto Sans 2.012 is where something went wrong:
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/71131343/d725e0de-13b4-41f3-ac4b-9fc52105be30)

**Comment by simoncozens** [comment]
Oh, *exasperated exclamation*. You're right. It's something to do with the ufomerge build process. hinted/unhinted builds are fine, full/googlefonts are broken.

**Comment by simoncozens** [comment]
I've fixed this in `ufomerge`; it'll be fixed next time Noto Sans gets built.
