### ISSUE TITLE
IPA primary stress symbol overlaps with following glyph in Arimo-Regular

### ISSUE THREAD

**Issue by Astavie** [notofonts/latin-greek-cyrillic#80]
### Title 
IPA primary stress symbol overlaps with following glyph in Arimo-Regular

### Font 
Arimo-Regular

### Where the font came from, and when
Pre-installed on Elementary OS 5.1.7 Hera, installed on 27th September 2020
Most likely came from the `fonts-croscore` ubuntu package

### Font Version
1.32

### OS name and version
Elementary OS 5.1.7 Hera

### Issue
  1. Steps to reproduce

type `ˈa` using the Arimo-Regular font

  2. Observed results

the primary stress mark overlaps with the latin letter a

  3. Expected results

the primary stress mark should precede the latin letter a

### Character data
`ˈa`

### Screenshot
![image](https://user-images.githubusercontent.com/7745457/94907014-c9fc5300-049f-11eb-953a-ad27925e606f.png)

**Comment by simoncozens** [comment]
Duplicate of #34.
